### PR TITLE
Exception Handling in Cpp

### PR DESCRIPTION
**Pull request by Pranshu321**
## Related Issue
- #1146 

## Proposed Changes
- Exceptional Handling in C++
- Well Documented Explanation of Exception Handling

## Additional Info
- In Cpp, there is code regarding the topic and in the readme, there is a full detailed explanation

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- In the readme file, I have explained in detail what, why, and types of exception handling.
- In the CPP file, I have given a detailed code of everything which I explain in the readme file.

Exception Handling is a process in which some conditions are taken care of which will lead to the crashing of software or the hanging of the system.

Gives a wider view of exception handling in c++.

#1146 

Simply run on any compiler like GCC etc.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| Exceptional Handling Output| 
image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Output is not understandable for a guy who is nobish..add some lines using cout to make output descriptive and understandable

**Comment by Pranshu321** [comment]
> Output is not understandable for a guy who is nobish..add some lines using cout to make output descriptive and understandable

@Mrjoy832 Sir, the changes proposed by you are implemented.

**Review by Lakhankumawat — APPROVED** [review]
Looks Awesome ✨🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Pranshu321 code ,

**Comment by Lakhankumawat** [comment]
CGC Continuous Good Contribution.
Your next prs have higher chances to get more level just mention your merged pr numbers in your next prs and we'll look if you are eligible for a pr level promoting.

**Pull request merged**
