### PR TITLE
Aggressive Cows Problem

### PR DESCRIPTION
**Pull request by dewanshiPaul**
## Related Issue
- Issue No #802 

## Proposed Changes
- Added a binary search problem for level-2

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

This is code for a problem known as aggressive cows. The statement is:
There is a new barn with N stalls and C cows. The stalls are located on a straight line at positions x1,….,xN (0 <= xi <= 1,000,000,000). We want to assign the cows to the stalls, such that the minimum distance between any two of them is as large as possible. What is the largest minimum distance?

Explanation of the problem statement with approach discussion and time complexity is added in readme file. This is a level 2 problem which was not present in repo and hence gives understanding of binary search related problems.

issue link: https://github.com/Lakhankumawat/LearnCPP/issues/802

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Readme screenshot
image
image
Code:
image
output:
image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Add image only in readme..dont seperately add into folder

**Comment by dewanshiPaul** [comment]
Ok only this change us required

**Comment by Mrjoy832** [comment]
> Ok only this change us required

put cpp file and readme into a separate folder and create PR ..either Your CPP file and readme will be scattered.

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Mrjoy832** [comment]
Listen We are not allowed to merge PR taking 10+ commits ...so  kindly keep an eye on this point

**Comment by dewanshiPaul** [comment]
i made necessary changes but cannot upload properly now

**Comment by dewanshiPaul** [comment]
so i deleted files and now want to add changes but not allowing can you help me

**Comment by Mrjoy832** [comment]
> i made necessary changes but cannot upload properly now

Whats the issue you are facing tell in discord LearnCPP group

**Comment by dewanshiPaul** [comment]
ok

**Comment by Mrjoy832** [comment]
Your readme and cpp will not be together how You created this PR ...previously I said that make a folder of your topic name and in the folder add cpp and readme...by this 2 will be together

**Comment by Mrjoy832** [comment]
check https://github.com/Lakhankumawat/LearnCPP/pull/1085

**Comment by dewanshiPaul** [comment]
Actually this is totally an new folder and as per recommendations given for problem statement we have to make a folder of level-2 and inside there readme and solution should be there so i kept it that way before

**Comment by Mrjoy832** [comment]
> Actually this is totally an new folder and as per recommendations given for problem statement we have to make a folder of level-2 and inside there readme and solution should be there so i kept it that way before

then create level-2/Cow.cpp and readme file

**Comment by Mrjoy832** [comment]
> > Actually this is totally an new folder and as per recommendations given for problem statement we have to make a folder of level-2 and inside there readme and solution should be there so i kept it that way before
> 
>Wait I will confirm You..work on other issue

**Comment by Mrjoy832** [comment]
@Lakhankumawat

**Comment by dewanshiPaul** [comment]
> > Actually this is totally an new folder and as per recommendations given for problem statement we have to make a folder of level-2 and inside there readme and solution should be there so i kept it that way before
> 
> then create level-2/Cow.cpp and readme file

I made like this only before with image in that folder just say me changes later

**Comment by Mrjoy832** [comment]
> > > Actually this is totally an new folder and as per recommendations given for problem statement we have to make a folder of level-2 and inside there readme and solution should be there so i kept it that way before
> > 
> > 
> > then create level-2/Cow.cpp and readme file
> 
> I made like this only before with image in that folder just say me changes later

Wait You will be informed

**Comment by dewanshiPaul** [comment]
For this if my commit count increases then it will not be accepted.. if so should i close this and make another pr in another branch and do it?

**Comment by dewanshiPaul** [comment]
@Mrjoy832

**Comment by Lakhankumawat** [comment]
Close the PR create a new PULL REQUEST with less number of commits in a fresh manner

Your Code Directory  will be along with file name please pay attention ` P-Problem Statements & Solution/2-Level 2/AggressiveCows.cpp`

and README changes inside `P-Problem Statements & Solution/2-Level 2/README.md`


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Pull request closed without merging**
