### PR TITLE
 Decimal to Binary Conversion 

### PR DESCRIPTION
**Pull request by aditim26**
## Related Issue
-  Program for decimal to binary conversion using stack(#1055)

- A decimal number can be converted to its binary equivalent by dividing the number by 2 till it can be no more divided and then printing its remainder in the reverse order.

- For example:
image

## Proposed Changes
- Added the program for issue #1055 
- Changes in the Readme file

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

In this PR I have added a program for converting any decimal number to its binary equivalent 

This PR is solving issue #1055 which was created by me.

Examples of the test cases are given below 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Screenshot #1    
Code                
image

Screenshot #2   
Output              
image

### CODE REVIEW

**Comment by aditim26** [comment]
sir this will be my third PR
link to my first and second PR are :
- https://github.com/Lakhankumawat/LearnCPP/pull/513
- https://github.com/Lakhankumawat/LearnCPP/pull/1091

**Review by Lakhankumawat — COMMENTED** [review]
LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
CGC - Level2

**Comment by Lakhankumawat** [comment]
@all-contributors please add @aditim26 code

**Pull request merged**
