### PR TITLE
Mirror of a Generic Tree

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Mirror of a Generic Tree is implemented.
## Related Issue
- #753 

## Proposed Changes
- Code to implement Mirror of a Generic Tree.
- Readme file for the same.

## Additional Info
-All kind of information is in the readme file as well as comment present in code file wherever necessary.
## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- I have implemented to calculate Mirror of a Generic Tree which is important concept as this problem shows size of the mirror image is the same as the size of the object and the distance between the image obtained is the same as the distance between the object from the mirror.

- This concept is not yet implemented and it solves understanding about Mirror image.

- It fixes issue #753 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code  |Output     |
|Screenshot (505) |Screenshot (506)|

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Don't just write code in algorithm try to explain the approach!

**Comment by Lakhankumawat** [comment]
> Don't just write code in algorithm try to explain the approach!

+1

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
README looks but do the required changes

**Comment by mdnazisharman2803** [comment]
@Lakhankumawat changes made as requested

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉🌟

**Comment by Lakhankumawat** [comment]
CGC ( Continuous Good Contribution ) increasing level of contribution seeing your efforts 🌟

**Comment by Lakhankumawat** [comment]
@all-contributors please add @mdnazisharman2803  code

**Pull request merged**
