### PR TITLE
Coin tower

### PR DESCRIPTION
**Pull request by Bhavneet345**
## Related Issue
- #350 
- Problem Statement - Whis and Beerus are playing a new game today. They form a tower of N coins and make a move in alternate turns. Beerus plays first. In one step, the player can remove either 1, X, or Y coins from the tower. The person to make the last move wins the game. Can you find out who wins the game?

## Proposed Changes
- Added the code for The Coin Tower problem using Dynamic Programming.
- Updated the README.md file.

## Additional Info
- The problem comes under the Game Theory domain of Competitive programming.
- The program follows the Dynamic Programming approach.
- This code solves an open issue https://github.com/Lakhankumawat/LearnCPP/issues/350.
- I have tested these changes on VS code using multiple inputs and matched the output with the expected output.
- This change will not affect or create conflict with any other code
- Time Complexity: O(n), n - total number of coins
- Space Complexity: O(n), n - total number of coins

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1| 
| ----------- |
| Code Snippet | 
Screenshot 2022-03-17 at 11 32 49 AM | 

| Screenshot #2| 
| ----------- |
| Output Snippet| 
| Screenshot 2022-03-17 at 11 38 37 AM |

### CODE REVIEW

**Comment by Bhavneet345** [comment]
@Lakhankumawat @miraj0507 pls review my pull request If you want any changes to be made pls tell, thank you.

**Comment by Bhavneet345** [comment]
@siddhi-244 @miraj0507 @Lakhankumawat  please review my pull request.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Don't add code in readme. Instead explain the algorithm! Resolve the merge conflicts

**Comment by Bhavneet345** [comment]
@siddhi-244 thank you for reviewing I will make the requested changes but how can I resolve the merge conflicts??

**Pull request closed without merging**
