### PR TITLE
Finding  All The Bridges In The Given Graph

### PR DESCRIPTION
**Pull request by Shweta597**
## Related Issue
- Code Added For issue #383  

## Proposed Changes
-  Added Code for finding all the bridges in F-FindBridges folder which is inside G-GraphAlgorithms Folder 
-  file name: FindBrides.cpp
- Created README.md inside F-FindBridges folder and added all the necessary information regarding Find Bridges in Graph.

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
1. Uncheck all the checks which do not apply to you
2. Modify README

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Shweta597** [comment]
Now can you review If there is anything else to modify

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Follow proper structure of Readme !

**Comment by siddhi-244** [comment]
Closing this pr!

**Pull request closed without merging**
