### PR TITLE
Direct Recursion

### PR DESCRIPTION
**Pull request by i-am-aisha**
## Related Issue
#1436 

## Proposed Changes
- Create a DirectRecursion.cpp file contain algorithm of direct recursion with  proper code and explanation.
- Update readme accordingly

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Code image
Screenshot (36)

Input image
Screenshot (34)

Output image
Screenshot (35)

### CODE REVIEW

**Comment by i-am-aisha** [comment]
@Mrjoy832 please review

**Comment by i-am-aisha** [comment]
@Mrjoy832  please let me know if have to do something in this PR.

**Review by Mrjoy832 — CHANGES_REQUESTED** [review]

**Comment by i-am-aisha** [comment]
@Mrjoy832 updated please check

**Comment by i-am-aisha** [comment]
@Mrjoy832 please review my pr

**Review by Mrjoy832 — APPROVED** [review]

**Comment by Mrjoy832** [comment]
## LGTM🌟🎉

**Comment by i-am-aisha** [comment]
@Lakhankumawat please have a look on my Pr

**Review by Lakhankumawat — APPROVED** [review]
## LGTM ✨🎉

**Comment by Lakhankumawat** [comment]
This is your last pr and you did well during the whole event , giving ya level 2 ✨

**Pull request merged**
