### PR TITLE
Middle element of the linked list(two pointer approach)

### PR DESCRIPTION
**Pull request by DlVYANSH**
## Related Issue
- #518 

## Proposed Changes
- Added the code file
- Updated the readme

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Screenshot (240)

### CODE REVIEW

**Comment by siddhi-244** [comment]
Resolve merge conflicts!

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Try to be more descriptive in Readme

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by DlVYANSH** [comment]
> Try to be more descriptive in Readme


Sorry but I have nothing more to add  in the readme. Everything is explained properly and even everything is explained in the image itself. If you have any suggestions I will add that into the readme.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Explain the question in readme first !

**Comment by DlVYANSH** [comment]
> Explain the question in readme first !

I have added the problem statement

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🌟💯

Great work @DlVYANSH  , keep contributing ...

**Comment by Lakhankumawat** [comment]
Constant good contribution increasing level ++ this time only

**Pull request merged**
