### PR TITLE
#367 Linked list Operations using class

### PR DESCRIPTION
**Pull request by VaishnaviMandloi**
## Related Issue
- Linked list with header node #367 

## Proposed Changes
- added code for Linked list with header node with comments (explanation) and user input function.
- added a explanation for  Linked list with header node in README file with image and mentioned points. 

## Additional Info
-Header linked list is linked list which have a header node at the beginning of the list . It make the program simple and faster as the list is never empty ,header node is always present . Therefore we can avoid cases for insertion or deletion at beginning.
- Tested with many input , screen shot of one of those is provided below.
- only 1 folder (having 2 files in it ): LinkedListWithHeaderNode is added into L-Linked list folder.
  1st file : LinkedListWithHeaderNode.cpp
   2nd file : Readme.md
- Time Complexity
- For create_list()
  O(n) ,where n is the number of node
- For display()
  O(n) ,where n is the number of node
- For addatend()
  O(n) ,where n is the number of node
- For addbefore
  O(n) 
- For addatpos
  O(n)
- For del()
  O(n) 
- For  reverse()
  O(n) ,where n is the number of node

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| code screenshot   | output screenshot  |
| code #367 learncpp  |   output #367 learncpp
   |

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
`L-LinkedList/LinkedListWithHeaderNode/LinkedListWithHeaderNode.cpp` -> ` L-LinkedList/LinkedListOperations/LinkedListOperations.cpp`

**Comment by VaishnaviMandloi** [comment]
@siddhi-244  change updated as told ,please review.

**Comment by Lakhankumawat** [comment]
I would recommend you to come up with somethign new

**Comment by VaishnaviMandloi** [comment]
@Lakhankumawat as classes are used by me insted of structure so can This issue can be taken as OPERATIONS OF LINKED LIST USING CLASS, 
As I made the contribution as linked list with headernode that why this problem arrived so if possible with OPERATIONS OF LINKED LIST USING CLASS please review it

**Comment by VaishnaviMandloi** [comment]
@Lakhankumawat thank you very much 
Is there any changes that I have to do now

**Comment by Lakhankumawat** [comment]
After going your code throughly i have sorry to say that i have to close your PR because your contribution is valid and you've worked but i don't see the difference you're saying i am using class they are using struct

Tomorrow one more guy will come changing the struct definition and will say my code is different you need to understand idea is same , whole implement is same except your class and i think you should start exploring repo and other pull request and come up with something new .
```
struct Node
{
   int data;
   struct Node *next;
} *first;

```

```
class Node
{
    public:
    int info;
    Node *link;
};


```

**Pull request closed without merging**
