### PR TITLE
Juggler sequence

### PR DESCRIPTION
**Pull request by Hend123**
## Related Issue
- Juggler Sequence #1068
- My Changes inside M-MathematicalAlgorithms folder -> Juggler Sequence folder.

## Proposed Changes
- Problem Statement
- Example
- Explanation
- Code
- Time Complexity & Space Complexity

## Additional Info
- [Link of the problem](https://www.geeksforgeeks.org/juggler-sequence/)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

First: decribe the problem: Juggler Sequence is a series of integer number in which the first term starts with a positive integer number a and the remaining terms are generated from the immediate previous term using Formulas.
Second: given example, Juggler Sequence starting with number 9: 
then output is : 9, 27, 140, 11, 36, 6, 2, 1
(Given a number n we have to print the Juggler Sequence for this number as the first term of the sequence. )
Third: Algorithm Using Iterative approach:
- print the first term.
- calculate terms until last term is not 1 using while loop.
- check if previous term is even or odd.
- calculate next term then print it.
Using Recursive approach:
- Output the value of N.
- If N has reached 1 end the recursion.
- Otherwise, follow the formula based on the number being odd or even and call
  the recursive function on the newly derived number.
Fourth write code.
Fifth: compute time complexity and space complexity
Final write README.

I have added the Problem Statement, Examples along with the Explanation on how to approach this problem, a commented Code and also written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Mathematical Algorithms i.e. Juggler Sequence and this problem helps in understanding the concept of Recursion.

I coded this problem in Code Blocks and tested the given problem on 6 test cases.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Example 1 | Example 2 |
| image | image    |

### CODE REVIEW

**Comment by Mrjoy832** [comment]
🌟 the repo and put tick on the box...

**Comment by Mrjoy832** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Hend123** [comment]
@Mrjoy832 iam updating read me and following guidelines

**Comment by Mrjoy832** [comment]
> @Mrjoy832 iam updating read me and following guidelines

Will be checked by eve

**Comment by Mrjoy832** [comment]
LGTM

**Comment by Hend123** [comment]
Required anything from me nor will wait review from admin only. 
What is meaning LGTM? 
@Mrjoy832

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]

**Comment by Lakhankumawat** [comment]
No response ?

**Comment by Hend123** [comment]
I make changes today

**Comment by Hend123** [comment]
I make changes

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

Good Contribution @Hend123 keep contributing , keep learning
>If you keep your contribution good for next prs as well i will increase level if you are found eligible.

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Hend123  code ,

**Comment by Hend123** [comment]
Thank you

**Pull request merged**
