### PR TITLE
#629RedundantParenthesis

### PR DESCRIPTION
**Pull request by dev24il**
**# Issue 629**
RedundantParenthesis #629 

# RedundantParenthesis
- Given a string of balanced expression, find if it contains a redundant parenthesis or not. A set of parenthesis are redundant if the same sub-expression is surrounded by unnecessary or multiple brackets. Print True if redundant, else False.
Note: Expression may contain ‘+‘, ‘*‘, ‘–‘ and ‘/‘ operators. Given expression is valid and there are no white spaces present.
- For example:
1. ((a+b)) can reduced to (a+b), this is Redundant
2. (a+b*(c-d)) doesn't have any redundant or multiple brackets

# Proposed Changes
- RedundantParenthesis code file added
- README.md added

# Additional Info
### Stack : Stack is a linear data structure which follows a particular order in which the operations are performed. The order may be LIFO(Last In First Out) or FILO(First In Last Out). 
image
Redundant : The expression should not have extra brackets.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Algorithm

We will use stack as a data structure to solve this problem.
1. We iterate through the given expression and for each character in the expression, if the character is an open parenthesis ‘(‘ or any operators, we push it to the stack.
2. If the character is close parenthesis ‘)’, then pop characters from the stack till matching open parenthesis ‘(‘ is found. 

## Output Screenshots
**Input 1:**
**((a+b))**
Screenshot (489)

**Input2:**
**(a+(a+b))**
Screenshot (490)

### CODE REVIEW

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Change Spacing inside `Redundant Parenthesis`

Follow camel casing for file naming `RedudantParenthesis.cpp`

Add Comments in your code 

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?

**Comment by dev24il** [comment]
@siddhi-244 please review my pr

**Comment by siddhi-244** [comment]
You haven't removed the spaces !

**Comment by dev24il** [comment]
> You haven't removed the spaces !

I have done please review it again

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You haven't removed the space from folder name as suggested by lakhan!

**Comment by dev24il** [comment]
> You haven't removed the space from folder name as suggested by lakhan!

I think now I have removed all the spaces as suggested please merge my pr @Lakhankumawat

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Explain the algorithm and don't add code there !

**Comment by dev24il** [comment]
> Explain the algorithm and don't add code there !

I have explained the algorithm in approach

**Comment by dev24il** [comment]
> > Explain the algorithm and don't add code there !
Ok

**Comment by dev24il** [comment]
> Explain the algorithm and don't add code there !

In README.md also I have to do

**Comment by siddhi-244** [comment]
> > Explain the algorithm and don't add code there !
> 
> In README.md also I have to do

In readme. You have added code under algorithm.  Try to add algorithm there !

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by dev24il** [comment]
> LGTM

Ok!

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🌟💯

Great work @dev24il  keep contributing ✨✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @dev24il  code ,

**Pull request merged**
