### PR TITLE
Reverse a Queue #269

### PR DESCRIPTION
**Pull request by Mrudula-Kulkarni**
## Related Issue
- Reverse a Queue #269
- Added the code implementation of Reverse a Queue with and without recursion
- Added the explanation of  Reverse a Queue in the README.md file

## Proposed Changes
- Added the code of Reverse a queue with and without recursion
- Added  README.md file of Reverse a queue with time and space complexity.
- Included the Images and Pseudo Code in the README.md file.

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1    
reverseQueue
| Screenshot #2
reverseQueue2

### CODE REVIEW

**Comment by Mrudula-Kulkarni** [comment]
Can you please review the PR

**Comment by Lakhankumawat** [comment]
///-----------------CheckList-------------------------///
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)




For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Remove the exe file, it's not needed !

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by Mrudula-Kulkarni** [comment]
Hello, Thank you for approving the changes
If everything is fine, can you please merge the PR?

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Mrudula-Kulkarni  code ,

**Pull request merged**
