### PR TITLE
Iterative Preorder and Postorder Traversal of Generic Tree

### LINKED ISSUE #1187: Iterative Preorder and Postorder Traversal  of Generic Tree
### Description

Preorder Traversal of a Generic Tree is similar to the preorder traversal of Binary Search Tree or Binary Tree with the only difference that is, all the child nodes of a parent are traversed from left to right in a sequence.

Post-order Traversal of a Generic Tree is similar to the postorder traversal of Binary Search Tree or Binary Tree with the only difference that is, all the child nodes of a parent are traversed from right to left in a sequence.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Iterative Preorder and Postorder Traversal of Generic Tree
## Related Issue
- #1187 

## Proposed Changes
- Code to implement Level order Traversal of a Generic Tree.
- Readme file for the same.
## Additional Info
- All kind of information is in the readme file as well as comment present in code file wherever necessary.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

I have implemented Iterative Preorder and Postorder Traversal of Generic Tree which is important concept as this problem shows that Preorder traverse gives the node values in a sequence of insertion. We can create a copy of the tree by traversing the source tree in this way. Postorder traverse can use this method to delete entire tree cause it visits leaf nodes first.

- This concept is not yet implemented and it solves understanding about Iterative Preorder and Postorder Traversal of Generic Tree

- It fixes #1187 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code | Output     |
|Screenshot (517)|Screenshot (524)|

### CODE REVIEW

**Comment by Mrjoy832** [comment]
change readme image by MS Paint or other resource

**Comment by mdnazisharman2803** [comment]
> change readme image by MS Paint or other resource

okk

**Comment by mdnazisharman2803** [comment]
> change readme image by MS Paint or other resource

@Mrjoy832  its fixed can you approve , thanks

**Comment by Mrjoy832** [comment]
image
spelling mistake ..rests are fine

**Comment by Lakhankumawat** [comment]
Generic Trees Everytime 😂😂
Doing Research or What !?

Do the required changes i'll merge it .

**Review by Lakhankumawat — APPROVED** [review]
Looks Generous ✨🎉

**Comment by mdnazisharman2803** [comment]
> Generic Trees Everytime 😂😂 Doing Research or What !?
> 
> Do the required changes i'll merge it .

Hahha 😅.  Less crowd here
Done changes

**Comment by Lakhankumawat** [comment]
Continuous Good Contribution ..

**Pull request merged**
