### PR TITLE
issue #623 The Perfect Number

### PR DESCRIPTION
**Pull request by ahmedmo112**
## Related Issue
- #623 
- I have add a new file named perfectNumber.cpp  in M-MathematicalAlgorithms

## Info 
I have developed program that check if the number is perfect or not by get all the divisors then get the sum of them 
if the sum equal the number then the number is perfect number

## Algorithm
step1 - take from user a number
step2 -get all numbers that can be divided 
step3 -get the sum of the number we get (divisors)
step4 -check if  sum and input number equals or not

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?

**Comment by Lakhankumawat** [comment]
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

**Comment by Lakhankumawat** [comment]
For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

**Comment by siddhi-244** [comment]
Closing this pr!

**Pull request closed without merging**
