### PR TITLE
OOPS - Operator Overloading [Updated README and removed all cpp files but one]

### PR DESCRIPTION
**Pull request by alyeyad**
## Related Issue
- Issue #491 

## Proposed Changes
- Changes from PR #506:
- Updated README file according to instructions
- Added only the CPP for binary operator overloading and removed other files (will make seperate PRs for them)
- Updated the CPP file to show more descriptive output.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      |
| ----------- |
| Binary Operator Overloading  |
|output-binary2|

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
YOUR README looks good , mentors will review your PR shortly stay tuned ...

**Comment by alyeyad** [comment]
Noted, will update it

**Comment by alyeyad** [comment]
Kindly review after updates

**Comment by alyeyad** [comment]
Solved conflict, kindly review @miraj0507

**Review by Lakhankumawat — APPROVED** [review]
LGTM ✨🎉

Good Contribution @alyeyad

**Comment by Lakhankumawat** [comment]
@all-contributors please add @alyeyad code ,

**Pull request merged**
