### PR TITLE
Stack ADT using Linked List

### PR DESCRIPTION
**Pull request by Arun9739**
## Related Issue
- #1045

## Proposed Changes
-  I have added the stack ADT file using linked list implemetation. The ADT functions can be used for any type of the data type. For the sake of simplicity i have used the int data type to demonstrate.

## Additional Info
- The code was tested and the results were upto the mark.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

The ADT functions can be used for any type of the data type. For the sake of simplicity i have used the integer data type to demonstrate. I have added all the basic functions of the stack, such as push, pop, creating a stack, counting number of elements etc. In the readme file of stack folder i have described about the time complexity, stack functions and the stack terms.

## Output Screenshots
| Screenshot #1      |
| ----------- | 
| Screenshot of output |
|image)|

### CODE REVIEW

**Comment by Arun9739** [comment]
@Lakhankumawat sir please review my pr

**Comment by Mrjoy832** [comment]
Hey! add a function to display all STACK elements before pop out

**Comment by Arun9739** [comment]
@Mrjoy832 Please review my pr. I have added the function for displaying stack elements.

**Comment by Arun9739** [comment]
@Mrjoy832 I have made the program to take inputs from the user. Plz look into it.

**Comment by Mrjoy832** [comment]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
LGTM ✨🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Arun9739  code ,

**Pull request merged**
