### PR TITLE
Create Parenthesis_Checker

### PR DESCRIPTION
**Pull request by vinaya563**
## Related Issue
- Parenthesis Checker using stacks (#335 )

## Proposed Changes
 
- Given an expression containing characters ‘{‘,’}’,'(‘,’)’,'[‘,’]’. We have to write a code to check whether an input string has valid parentheses.
- An input string is valid if:

Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

A c++ code to check whether the expression entered is balanced or not using stacks.
An input string is valid if:
Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.

Example –

i) {[]}) – Invalid

ii) {()}[] – Valid

The title of this request is according to the problem it solves, as the isuue checks whether the expression contains valid parenthesis or not ,so is the title of the file 

This change is required as only few questions are available in the stack file 
,in order to cover all the stack related questions ,This particular change is required.

The particular code has been run in Devc++ ide of c/c++ and all the edge test cases have been passed.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
///--------------------Pull Requests--------------------///

1. Short Description or CheckLists

Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.



///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by vinaya563** [comment]
@Lakhankumawat  I have done the cahnges as you said ,
and regarding the documentation ,This particualar issue has already been mentioned as an application of stack ...
Do i again have to update the documentation or is it sufficient ?

**Comment by Lakhankumawat** [comment]
You have not pushed any changes yet , please check again!

**Comment by Lakhankumawat** [comment]
Starr the REPO

image
CLick on the star top right corner make it look yellow

**Comment by vinaya563** [comment]
@Lakhankumawat  actually someone has already added the required readme file and documentation in the stacks file ..so whats the next step i have to do ?

**Comment by Lakhankumawat** [comment]
You have to update the README according to your type od contribution 


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Pull request closed without merging**
