### PR TITLE
Sorted array to bst

### PR DESCRIPTION
**Pull request by ritikagarg0326**
- Converted sorted array to bst
## Related Issue
 - #793  

## Proposed Changes
- Code to convert array to bst.
- Readme file.

## Additional Info
- In the readme, I have added the properties, algorithms, and related comments in the code. Comments are present wherever they are necessary.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- I have converted an array into a height-balanced tree which is an important concept of a binary tree as it tells that the binary tree in which the left and right subtrees of every node differ in height by no more than 1 is called a height-balanced tree and also shows how can we convert an array to that.

- This concept is not yet implemented and it shows how can we convert an array to a bst.

- It fixes issue #793 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code  | Output     |
|Screenshot (254)| outputgssoc
    |

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Can uh explain the algorithm in steps?

**Comment by ritikagarg0326** [comment]
@siddhi-244 requested changes are made, please review it.

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Your README looks great but you forgot to add working image

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)


some of the mentors will verify your code shortly

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add the table of contents too. Refer the other prs.

**Comment by Lakhankumawat** [comment]
@all-contributors please add @ritikagarg0326 code ,

**Pull request merged**
