### PR TITLE
Armstrong number

### PR DESCRIPTION
**Pull request by aparnamittal**
## Related Issue
#1061

## Proposed Changes:

An integer number is called Armstrong number if sum of the cubes of its digits is equal to the number itself.
For example: 370 is an armstrong number because:

370 =>
= 333 + 777 + 000
= 27 + 343 + 0
= 370

image

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

## Algorithm:

1. The number of digits in n is determined and found out.
2. The sum of digits of a number are found by performing n mod 10, where mod is called the remainder operation.
3. The individual digit is then raised to the power (number of digits) and stored.
4. The number is then divided by 10 in order to obtain the second digit.
5. All the above 3-steps numbered Steps 2, 3 and 4 are performed until the value of n is greater than 0.
6. When the n is less than 0, end the while loop.
7. Check the sum obtained or Armstrong value is the same as the original number
8. When yes, the number is labelled an Armstrong number

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
example of armstrong number :
image

example of not a armstrong number :
image

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Try to add some images to explain the example better !

**Comment by aparnamittal** [comment]
ma'am pls review my PR I have made the changes.

**Comment by aparnamittal** [comment]
@siddhi-244  ma'am pls review my PR I have made the changes.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by aparnamittal** [comment]
**sir this is my 3 PR 
my 1 PR is merged** (https://github.com/Lakhankumawat/LearnCPP/issues/527 )
**and 2 PR is under review** https://github.com/Lakhankumawat/LearnCPP/pull/1069

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨
Good Work @aparnamittal  contiuous good contribution -1 

Will increase level of your 3rd pr congo 🎉🎀

**Comment by Lakhankumawat** [comment]
@all-contributors please add @aparnamittal  code ,

**Pull request merged**
