### PR TITLE
Trie Data Structure Implementation

### PR DESCRIPTION
**Pull request by Pranshu321**
## Related Issue
- #1211 

## Proposed Changes
- Trie implementation code.
- Trie implementation Readme added.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

In Readme, I have explained 
- What is Trie?
- How Insert and Search Function works?
- What's Node structure?

Gives a Basic idea about trie data structure.

#1211 

On any Cpp Compiler

- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1|
| ----------- | 
| Trie Implementation code Output  | 
image

### CODE REVIEW

**Comment by Pranshu321** [comment]
@Mrjoy832 are there any changes here in this PR?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 are there any changes here in this PR?

Sorry, but It's under another mentor ..She will check

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by Lakhankumawat** [comment]
image

**Comment by Pranshu321** [comment]
> image

**Naming corrected as said the rules. @Lakhankumawat **

**Review by Lakhankumawat — APPROVED** [review]
LGTM ✨🎉

**Comment by Lakhankumawat** [comment]
Good Contirbution .

**Pull request merged**
