### PR TITLE
Added implementation of Red Black Trees

### PR DESCRIPTION
**Pull request by Princeton21**
## Related Issue
- Pull Request for (#733  )issue

## Proposed Changes
- Implemented the program for insertion, deletion and searching of the red black tree
- Added the documentation in a README.md in the respective file location

## Additional Info
- Created Changes in readme.md file
- Added a folder for Red Black Trees [here](https://github.com/Lakhankumawat/LearnCPP/tree/main/T-Tree/B-BinarySearchTree)
- This folder contains two files namely
    - README.md
    - Red Black Tree.cpp

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots

Output of the Red Black tree.cpp program 

image      

 Preview of the readme.md file 

image

### CODE REVIEW

**Comment by Princeton21** [comment]
@Lakhankumawat @Mrjoy832  Kindly review my pull request and tell me if there are any changes

**Comment by Mrjoy832** [comment]
- Put ticks on proper all boxes
- why 3 files are changed

**Comment by Princeton21** [comment]
I have created a separate readme for red-black trees and have added its details in the general readme of the binary search tree folder

**Comment by Princeton21** [comment]
> * Put ticks on proper all boxes
> * why 3 files are changed


image

I have created the respective changes as mentioned my pull request under additional info

**Pull request closed without merging**
