### PR TITLE
Implementing two stacks using a single array

### PR DESCRIPTION
**Pull request by Arun9739**
## Related Issue
- #1397

## Proposed Changes
- Added the code file for implementation of two stack using a single array
- Upated the readme file accordingly

## Additional Info
- I have created a program in which two stacks can be implemented using a single array.
- Stack_1 starts from 0th position and moves towards the rightmost side.
- Stack_2 starts from (n-1)th index and moves left side.
- The code was tested and it is giving desired result.

Impotant keywords :
- arr : This is the array which holds two stacks
- top_1 : A reference to top data of stack 1
- top_2 : A reference to top data of stack 2

There are 6 methods used in this program :
- push_1() : This function pushes the data into the stack 1
- push_2() : This function pushes the data into the stack 2
- pop_1() : This function pops the data from the stack 1
- pop_2() : This function pops the data from the stack 2
- dispaly_1() : This function displays the stack 1 elements
- display_2() : This functiom dispalys the stack 2 elements
 
## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- |
| image|

## Code Screenshots 
image
image
image
image
image

### CODE REVIEW

**Comment by Arun9739** [comment]
@Mrjoy832 please review my pr.

This is my fourth pr. My first three pr's are :
- #1046 
- #1152 
- #1395

**Comment by Arun9739** [comment]
@aditi944 pleasae review this pr

**Comment by aditi944** [comment]
Please add screenshots of the code and output all together

**Comment by Arun9739** [comment]
@aditi944 I have done the changes. Please review.

**Comment by aditi944** [comment]
Can you please output the complete stack after every push and pop operation? So that one can see if the elements are getting pushed in the required order.

**Comment by Arun9739** [comment]
@aditi944 I have done the changes. Also I have updated the output and code screenshots. Plesae review.

**Comment by Lakhankumawat** [comment]
Resolve Merge Conflicts please

**Comment by Arun9739** [comment]
@Lakhankumawat I have done the changes

**Pull request merged**
