### PR TITLE
created firstandlastindex algorithm using binary search

### PR DESCRIPTION
**Pull request by ritikaaaa177**
- You are given a sorted array "arr" of n elements. Given a number d, you have to find it's first occurrence in the array as well as its last occurrence. The array may contain duplicates.

Example

Find first & last occurrence of 33 in the given array:

Array arr = {1, 2, 9, 15, 22, 33, 33, 33, 33, 33, 39, 40, 55, 66, 77}.

Hence, the answer will be 5 and 9 respectively (0-based indexing).

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |
Screenshot (435)

### CODE REVIEW

**Comment by ritikaaaa177** [comment]
Hello @Lakhankumawat please review my code

**Comment by iamgunjan** [comment]
@ritikaaaa177 kindly add screenshots of output and complete your checkboxes

**Comment by ritikaaaa177** [comment]
okay @iamgunjan i will do it

**Comment by ritikaaaa177** [comment]
Hi @iamgunjan have a look I made the required changes

**Comment by siddhi-244** [comment]
//-----------------CheckList-------------------------/// Make sure your Pull Request is descriptive and complete the checklist . I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks. ///------------------Description -----------------------/// Let me show you how to check the check list , there should be no space inside brackets like [x] `[x]` - [x] Checklist - [ ] Or you can just check them from outside without doing any of these - [x] âœ¨ I have added tests to cover my changes. - [x] ðŸš© All new and existing tests passed. - [ ] ðŸŒŸ ed the repo 1. Starr the repo if you haven't ! 2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ? ///----------------------PR README --------------------/// You need to follow particular guidelines for your README , please follow these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Pull request closed without merging**
