### PR TITLE
Updated rat in maze

### PR DESCRIPTION
**Pull request by Garvit-Gandhi**
Issue #109: Improve RatInMaze.cpp

## Proposed Changes

The ability to dynamically make the maze and add obstacles at runtime.

## Additional Info
- Any additional information or context-
 
Edited the RatInMaze.cpp in B-Backtracking.
Updated README.MD

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Added the ability to describe the maze at runtime.
Added more comments.
Added conditions to stop the entrance and exit from being blocked.

In the previous program, the code had to be edited every time to try a new maze 
and the maze needed to be pre-defined, this program solves both the problems

https://github.com/Lakhankumawat/LearnCPP/issues/109

I used various mazes to see if the desired output was achieved.
checked the edge cases where the entrance/exit of the maze was blocked.

The tests were done using the local windows debugger of Visual Studio
Test case inputs are shown in the screenshots of the output.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Testcase 1  | Testcase 2    |
| 
Screenshot (32)
  | 
Screenshot (34)
     |
Screenshot (35)

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.



///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by miraj0507** [comment]
The readme can be made a little elaborate , the code looks great to me @Garvit-Gandhi

**Comment by miraj0507** [comment]
Kindly look into the readme and codebase @n4i9kita the code looks fine the readme doesnt.

**Comment by aditi944** [comment]
closed

**Pull request closed without merging**
