### PR TITLE
Finding GCD and LCM using Recursion

### PR DESCRIPTION
**Pull request by Arun9739**
## Related Issue
- #1114 

## Proposed Changes
- Creating a proram with appropriate comments which calculates GCD and LCM of two given numbers using the concept of Recursion.
- Creating a README.md file for my sepearte folder, so that it can describe evrything about Recursion, GCD and LCM.

## Additional Info
- The result of program are verified to be correct.

## About the Program :
- I have basically created two functions namely calculateGCD() and calculateLCM()
- calculateGCD() takes two integer inputs and returns their GCD
- It calculates the GCD recursively.
- Another function calculateLCM() calcultes the LCM by taking two inputs. 
- The calculateLCM() function calls calculateGCD() so that it can directly calculate the LCM without any further iteration..
- I have created the README.md file where I have explained in detail what is necessity of the recursion, how recusion works, what is the difference between the recursive approach and iterative approach. I have also mentioned the time complexity, space complexity, advantages and disadvantages.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| image  | image   |

### CODE REVIEW

**Comment by Arun9739** [comment]
@Mrjoy832 please review my pr. 
This is my second pr.
My first successfully merged pr is #1046(Stack ADT using linked list)

**Comment by Mrjoy832** [comment]
> @Mrjoy832 please review my pr. This is my second pr. My first successfully merged pr is #1046(Stack ADT using linked list)

Hey ...all is good ..but in R-Recursion folder there is already a README...it will be preferable if you add your readme content  into that readme.....and only create one new file i.e. cpp file...**update the pre-existed Readme..don't create new one**

**Comment by Arun9739** [comment]
@Mrjoy832 ok sir I got it. I will close this pr and create new one with only one file and updated readme.md

**Comment by Mrjoy832** [comment]
> @Mrjoy832 ok sir I got it. I will close this pr and create new one with only one file and updated readme.md

As all was good ...dm me on discord with PR link after creating PR

**Pull request closed without merging**
