### PR TITLE
Min cost climbing stairs

### PR DESCRIPTION
**Pull request by Shweta2024**
## Related Issue
Min Cost Climbing Stairs #1011
## Proposed Changes
I have added the following things: -

- Problem Statement
- Examples
- Explanation
- Code
- Time Complexity & Space Complexity
- Screenshot of Output

## Additional Info
- [Link of the Problem](https://leetcode.com/problems/min-cost-climbing-stairs/)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

#### Min Cost Climbing Stairs

We were supposed to find the minimum cost to reach the top of the floor., provided we can either make one jump or 2 jumps at a time and can either start from the step with index 0, or the step with index 1.

I have added the Problem Statement and Examples along with the Explanation on how to approach this problem, a commented Code, and also written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Dynamic Programming i.e. Min Cost Climbing Stairs and this problem helps in understanding the concept of Dynamic Programming.

I coded this problem in VS Code and tested the given problem on the test cases in the range of 1 to 44. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Output for cost = [10,15,20]  | Output for cost = [1,100,1,1,1,100,1,1,100,1]    |
|  |  |

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
In explanation section,  the bullet points are not properly edited. For eg see your example section and use same editing

**Comment by Shweta2024** [comment]
> In explanation section, the bullet points are not properly edited. For eg see your example section and use same editing

Request changes have been made please review my PR.
Thank you

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
LGTM ✨🎉

**Comment by Shweta2024** [comment]
> 

Thank you sir

**Comment by Shweta2024** [comment]
> LGTM ✨🎉

Thank you sir

**Pull request merged**
