### PR TITLE
Search element in rotated sorted array using binary search #635

### PR DESCRIPTION
**Pull request by ShruthiKartik**
## Related Issue
-    Search element in rotated sorted array using binary search #635
-    Added the C++ code of the above problem.
-    Added the explanation of the logic used in this problem.
## Proposed Changes
- Change 1  Added the C++ code of the problem with time and space complexity along with comments.
- Change 2  Added the explanation of the above problem in README.md of SearchingAlgorithms Directory

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

I have solved this problem using Binary Search. I have also explained both naive(Linear Search) and optimal approach(Binary Search) to solve the above problem. I have also added the Leetcode link of the above problem in README file. I have also added the time and space complexity along with comments wherever necessary in the code.

Test Details:

I have run the the test cases on GCC Compiler. 
Test Case 1:
arr=[4,5,6,7,0,1,2] 
n=7 , element=2
Output: 6

Test Case 2:
arr=[12,14,18,21,3,6,8,9]
n=8, element=18
Output: 2

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Test Case 1: 

image

Test Case 2:

image

### CODE REVIEW

**Comment by siddhi-244** [comment]
Resolve conflicts !

**Comment by ShruthiKartik** [comment]
@siddhi-244 How to resolve the conflicts? It's coming because of the readme file .

**Comment by siddhi-244** [comment]
> @siddhi-244 How to resolve the conflicts? It's coming because of the readme file .

Yes. It's coming because of readme file. You can refer some YouTube videos to do so !

**Comment by ShruthiKartik** [comment]
@siddhi-244 Okay! I will do it after 2 weeks as my exams are there.

**Comment by ShruthiKartik** [comment]
@siddhi-244 I have resolved the conflicts. Please check.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
There are 3 files commited !  Could you please look into it !

**Comment by ShruthiKartik** [comment]
@siddhi-244 Actually that is exe file which also got committed. So, should I delete it?

**Comment by ShruthiKartik** [comment]
> @siddhi-244 Actually that is exe file which also got committed. So, should I delete it?

@siddhi-244 I am closing this PR and creating a new one.

**Pull request closed without merging**
