### PR TITLE
Pascal's Triangle

### PR DESCRIPTION
**Pull request by SiddhantPawar03**
## Related Issue
-Issue No: #358

## Checklist

- [X] ✅ My code follows the code style of this project.
- [X] 📝 My change requires a change to the README.
- [X] 🎀 I have updated the README accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by siddhi-244** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by siddhi-244** [comment]
> > You need to follow particular guidelines for your README , please follow these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) for more please go through these [here](https://youtu.be/7UgC3HDETRA)
> 
> @siddhi-244 hope I covered all the points mentioned by you :)

No you haven't! I can't see the readme file.

**Comment by SiddhantPawar03** [comment]
> > > You need to follow particular guidelines for your README , please follow these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) for more please go through these [here](https://youtu.be/7UgC3HDETRA)
> > 
> > 
> > @siddhi-244 hope I covered all the points mentioned by you :)
> 
> No you haven't! I can't see the readme file.

Added readme file!
Let me know about same.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by Lakhankumawat** [comment]
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

**Comment by Lakhankumawat** [comment]
Rename file from `Vector_Pascal'sTriangle.cpp` to `PascalsTriangle.cpp`

**Comment by Lakhankumawat** [comment]
Where is main function for your code you've just made a class and no starter function where you take input from user and print a pascal triangle based on input value .

**Comment by Lakhankumawat** [comment]
Follow these guidelines for your code "Your problem statement solution should be efficiently written with proper code / comments / time complexity / space complexity / link to problem statement in code file"

**Comment by Lakhankumawat** [comment]
No response from the contributor of the Pull Request !

**Pull request closed without merging**
