### PR TITLE
#330: Created a C++ file and updated readme for Equal sum partition

### PR DESCRIPTION
**Pull request by AastikSharma05**
## Related Issue
- The problem is to tell if a given array can be divided into 2 subsets such that sum of both the subsets is same. (Issue: #330  )
- Added the code implementation of Equal Sum Partition Problem using dp.
- Added the explanation of Equal Sum Partition Problem in the README.md file.

## Proposed Changes
- Added the code of Equal Sum Partition Problem using dp.
- Added README.md file of Equal Sum Partition Problem with time and space complexity.

## Additional Info
- This code uses dynamic programming. 
- This problem is a variation of 0-1 Knapsack problem.
- This is one of the commonly asked interview questions and the concept of this question helps us to solve many more problems based on subsets.
- This code solves an open issue #330 
- I have tested these changes on VS code  using multiple inputs and matched the output with the expected output.
- This change will not affect or create conflict with any other code
- Time Complexity : O(sum*n)
- Space Complexity: O(sum*n)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Issue: #330 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Readme preview|
Screenshot 2022-03-05 135044
 Code snippet    |
|   |  
Screenshot 2022-03-05 135122

### CODE REVIEW

**Comment by iamgunjan** [comment]
It's good to go from my side...

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🚩

**Comment by Lakhankumawat** [comment]
@all-contributors please add @AastikSharma05 code ,

**Pull request merged**
