### PR TITLE
Create String Length Encoding

### PR DESCRIPTION
**Pull request by Meaha7**
I have added a program on string length encoding.
kindly merge it

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Thank you @Meaha7  for showing your interest in submitting this program but it needs some improvements

1. Instead of making string fixed , take the input from user .
2. I hope you are clear with idea why we use encoding data , your program works fine with your string it reduces string size significantly , but it may not work for string like `who let the dogs out`  i mean which have space and non common adjacent words .

> Please try to make it more efficient .😄

**Comment by Meaha7** [comment]
Okayy!! I will try it

**Comment by Meaha7** [comment]
I have done it.Kindly check!!

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Okay but the second 
> I hope you are clear with idea why we use encoding data , your program works fine with your string it reduces string size significantly , but it may not work for string like who let the dogs out i mean which have space and non common adjacent words .

change is still missing

**Comment by Meaha7** [comment]
Sorry I am unable to do it

**Comment by Lakhankumawat** [comment]
Okay no worries @Meaha7 thanks for your interest ,  there is still much more you can contribute .

Happy Coding !!

**Pull request closed without merging**
