### PR TITLE
detect a cycle in a linked list

### PR DESCRIPTION
**Pull request by Purva-Gharat**
## Related Issue
#1354 

## Proposed Changes
Wrote a code for the singly linked list to detect a cycle in a linked list

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

## Output 
Input:
 Head = [1,2,3,4]
Output:
 true
Explanation: Here, we can see that we can reach node at position 1 again by following the next pointer. Thus, we return true for this case.

## Screenshots

Code -
image

Output -
image

### CODE REVIEW

**Comment by aditi944** [comment]
Please add screenshots of code with proper comments and of output

**Comment by Purva-Gharat** [comment]
> Please add screenshots of code with proper comments and of output

added..please check

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Purva-Gharat code ,

**Comment by Purva-Gharat** [comment]
Thank you so much!

**Pull request merged**
