### PR TITLE
Created Right Side View of BT

### PR DESCRIPTION
**Pull request by R-Ayush777**
Created Right Side View of BT and it's Solution approach to readme file.

## Related Issue
- The problem is Given an Given a binary tree, write an efficient algorithm to print its right view.
( issue number https://github.com/Lakhankumawat/LearnCPP/issues/1342 )

## Proposed Changes
- Added the implementation of Right Side View of BT.
- Added README.md file of Problem with time complexity and solution approach.

## Additional Info
- This code solves an open issue https://github.com/Lakhankumawat/LearnCPP/issues/1342
I have tested these changes on VS code using multiple inputs and matched the output with the expected output.
This change will not affect or create conflict with any other code.
Time complexity: O(N)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code Snippet  | Readme Snippet     |
| image  | image     |

### CODE REVIEW

**Comment by R-Ayush777** [comment]
@Mrjoy832 Please review my PR.

**Comment by R-Ayush777** [comment]
@aditi944 Please review my PR.

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🎉✨

**Comment by R-Ayush777** [comment]
@Lakhankumawat Can you elaborate where actually conflict is I am unable to track.

**Comment by Lakhankumawat** [comment]
Okay , DM Me the PR number in discord please

**Pull request closed without merging**
