### PR TITLE
Cousins binary tree

### PR DESCRIPTION
**Pull request by Shweta2024**
## Related Issue
- Cousins in Binary Tree #1482

## Proposed Changes
- Add code of Cousins in Binary Tree
- Update README.md

## Additional Info
- [Link of the Problem Statement](https://leetcode.com/problems/cousins-in-binary-tree/)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to find if the given two nodes are cousins or not.

I have added the Problem Statement, Examples, Algorithm on how to approach this problem, a commented Code,  and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Binary Tree i.e. Cousins in Binary Tree and this problem helps in understanding the concept of Binary Tree.

I coded this problem in VS Code and tested the given problem under the Constraints: :- 
- The number of nodes in the tree is in the range [2, 100].
- 1 <= Node.val <= 100
- x != y
 And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Input root = [1,2,3,4], x = 4, y = 3  | Input root = [1,2,3,null,4,null,5], x = 5, y = 4  |
| image | image  |

### CODE REVIEW

**Review by Mrjoy832 — APPROVED** [review]

**Comment by Mrjoy832** [comment]
LGTM🌟

**Comment by Shweta2024** [comment]
@Lakhankumawat 

Please review my pr  :) 

These are my previous PRs:-  
Climbing stairs #1010
Min cost climbing stairs #1078
Unique paths #1110
Unique paths II #1115
Minimum Falling Path Sum #1139
Knapsack with duplicate items #1227
Coin change #1278
Official README.md #1336

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🚩

**Review by Lakhankumawat — COMMENTED** [review]
## LGTM 💎🎉

**Pull request merged**
