### PR TITLE
The Knight’s tour problem

### LINKED ISSUE #1249: The Knight’s tour problem
### Description

Given a N*N board with the Knight placed on the first block of an empty board. Moving according to the rules of chess knight must visit each square exactly once. Print the order of each cell in which they are visited.

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
-  The Knight’s tour problem | Backtracking
## Related Issue
- #1249 

## Proposed Changes
- Code to implement Level order Traversal of a Generic Tree.
- Readme file for the same.

## Additional Info
- All kind of information is in the readme file as well as comment present in code file wherever necessary.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- I have implemented The Knight’s tour problem which is important concept as this problem is implemented using backtracking. Problems  bases on backtracking can only be solved by trying every possible configuration and each configuration is tried only once. 

- This concept is not yet implemented and it solves understanding about backtracking that can be used in chess type of problems.

- It fixes #1249 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1 |
| ----------- |
| Code  |
| Screenshot (553) |

| Screenshot #2 |
| ----------- |
|Output  |
|Screenshot (555)|

### CODE REVIEW

**Comment by Mrjoy832** [comment]
image
You have not fixed any issue..You added new content ...so do tick only on new feature

**Comment by mdnazisharman2803** [comment]
@Mrjoy832  done

**Comment by Mrjoy832** [comment]
image
This changes are pending

**Comment by mdnazisharman2803** [comment]
@Mrjoy832  all links has been fixed 🙂

**Comment by Mrjoy832** [comment]
LGTM🌟

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

**Pull request merged**
