### PR TITLE
Cartesian product

### PR DESCRIPTION
**Pull request by aditim26**
## Related Issue
- Cartesian Product of set (#511 )

   Cartesian product of two set A and B (A × B) is the set of all ordered pairs of elements that can be formed from set A and B
  Eg: Set A = {1,2,3}
        Set B = {4,5}
        A x B = {{1,4},{1,5},{2,4},{2,5},{3,4},{3,5}}

## Proposed Changes
- Added a program for finding the cartesian product 
- changes in the Readme (definition and properties)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- This pr has solved issue #511 (Cartesian Product of Two Sets) 

- It has solved the issue which was created by me 

- Examples of the test cases which the code has passed are given below 

- The changes in this PR will have no effect on other codes that are already present in the file  

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Screenshot #1 
Code
image

Test Case #1 
image

Test case #2
image

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by aditim26** [comment]
@Lakhankumawat sir, I have made changes in the readme and description pls check it.

**Comment by Lakhankumawat** [comment]
Uncheck all the checks which do not apply to you

**Comment by aditim26** [comment]
Sir, I have unchecked them pls review them.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by Lakhankumawat** [comment]
LGTM 💯

**Comment by Lakhankumawat** [comment]
@all-contributors please add @aditim26  code ,

**Pull request merged**
