### PR TITLE
Implementation Of Queue Using Array

### LINKED ISSUE #1116: Array Implementation Of Queue
### Description

In this issue, I will implement queue using array.
I will show the different operations such as insertion, deletion and traversal in a queue

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

### PR DESCRIPTION
**Pull request by Sukriti-m**
## Related Issue
- Implementation Of Queue Using Array (Closes #1116 )

## Proposed Changes
- Implementation of Queue using Array performing different operations such as insertion, deletion and display of elements in a queue.

- Changes in the readme

## Additional Info
- Organize the content of the readme

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

1.  Implementation of Queue using Array performing different operations such as insertion, deletion and display of elements in a queue.

2. I have created 3 functions: 

- Insert() -To insert elements
- Delete() -To delete elements
- Display() -To display elements

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Test Case 1  | Test Case 2     |
| 
q
 |     
q1
  |

@Lakhankumawat  @Mrjoy832  Please review this PR.

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Everone has colleges...please be patient

**Comment by Sukriti-m** [comment]
> Everone has colleges...please be patient

Yes, I understand. Sorry for tagging y'all.

**Comment by Mrjoy832** [comment]
LGTM 🌟

**Comment by Sukriti-m** [comment]
I have made the required changes.

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Sukriti-m  code ,

**Pull request merged**
