### PR TITLE
Stack, Queue, Deque and Priority Queue in STL Folder

### PR DESCRIPTION
**Pull request by nikhil25803**
This is PR corresponding to issue #182 
Added Stack, Queue, Deque, and Priority Queue in the STL folder with a readme file of each.

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Hey @nikhil25803  , make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


In this case you erased whole template so create a new pull request closing this one or copy from other Pr's and fill it .

**Comment by nikhil25803** [comment]
# Related Issue  
### This is the Pull Request regarding issue #182 

# Objective   
### To add Stack, Queue, Deque, and Priority Queue files in the STL folder of the repository

# Checklist 
### 1. I have gone through the contribution guidelines
### 2. I made my changes in the proper directory i.e in the STL folder
### 3. I added Stack, Queue, Deque, and Priority Queue in separate folders respectively
### 4. Each folder have 3 files
### 5. One file contains basic information like declaration and initialization
### 6. Another file contains the operations involved in the respective container
### 7. And the last one is a README file containing insights of the container like definition, syntax declaration, and list of operations.
### 8. ***All the programs are running without any error***

# Screenshots : 
Stack
Queue
Priority Queue
Deque

**Comment by Lakhankumawat** [comment]
changes in bunch are not welcomed , thanks

**Comment by Lakhankumawat** [comment]
One Commit at a time with two files only one issue code c++ file and other README file , what you are trying to actually do is contributing many many files at a time

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
Either create a new pull request with less file additions at a time or close this PR

**Pull request closed without merging**
