### PR TITLE
Height of Binary Tree

### PR DESCRIPTION
**Pull request by Purvak-10**
## Binary Tree details 
- Binary Tree details, issue number #302 

## I added algorithms to find:
- Number of leaf nodes in the binary tree
- Number of Internal nodes in the binary tree
- Total number of nodes in the binary tree
- Height of the binary tree

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Output with 7 elements in tree:
```
                 100
           /              \
        30                150
     /    \             /      \
  20       50          122      188
```
Height of tree: 3
o_p4

Output with 7 elements in tree:
```
100
  \
   120
      \
      130
         \
         140
            \
            150
              \
              160
                 \
                 170
```
Height of tree: 7
o_p5

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
1. Paste Some output screenshots in your PR

**Comment by Purvak-10** [comment]
> 1. Paste Some output screenshots in your PR description
> 2. Add atleast one image to your README showing working of your code .
> 
> You need to follow particular guidelines for your README , please follow these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) for more please go through these [here](https://youtu.be/7UgC3HDETRA)

@Lakhankumawat @miraj0507 sir i have done the changes, please review the pr.

**Comment by miraj0507** [comment]
This looks good to me

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯👏

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Purvak-10  code ,

**Pull request merged**
