### PR TITLE
Searching Algorithm - Sequential and Binary Search 

### PR DESCRIPTION
**Pull request by janhavikale06**
## Related Issue
#727  

## Proposed Changes
- Added a code for #727 

## Additional Info
- Sequential Search is used for unsorted and unordered small list of elements.
- It has a very simple implementation.
- Best-case complexity is O(1) where the element is found at the first index.
- Worst-case complexity is O(n) where the element is found at the end of array or element is not present in the array.
- Space complexity : O(1)

- Binary Search is an efficient algorithm for finding an element from a sorted array.
- It is used to narrow the search. For large lists of data, it works significantly better than Sequential Search.
- Time complexity : O(log n)
- Space complexity : O(1)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
LinearSearch
BinarySearch

### CODE REVIEW

**Comment by janhavikale06** [comment]
Hey @Mrjoy832 , please do check the changes.

**Comment by Mrjoy832** [comment]
Your File name is TOO odd...keep readme.md & SequentialAndBinarySearch.cpp

**Comment by janhavikale06** [comment]
> Your File name is TOO odd...keep readme.md & SequentialAndBinarySearch.cpp

Okay got it

**Comment by janhavikale06** [comment]
Hey @Mrjoy832 , can you check the changes I've done and please let me know if there are any changes required ?

**Comment by Mrjoy832** [comment]
Linear & Binary Seacrh is already there ...
https://github.com/Lakhankumawat/LearnCPP/tree/main/S-SearchingAlgorithms
You may close this and can add any problem regarding searching algo

**Pull request closed without merging**
