### PR TITLE
Level order Traversal of a Generic Tree

### LINKED ISSUE #1028: Level order Traversal of a Generic Tree
### Description

 The problem here deals with printing the tree in levels from left to right where the nodes are separated by spaces.

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Level order Traversal of a Generic Tree is implemented.
## Related Issue
- #1028 

## Proposed Changes
- Code to implement Level order Traversal of a Generic Tree.
- Readme file for the same.
## Additional Info
- All kind of information is in the readme file as well as comment present in code file wherever necessary.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

I have implemented Level Order Traversal of a Generic Tree which is important concept as this problem shows that Level order traversal is actually a Breadth-First Search, which can be used to solve many problems in graph theory, for example: Finding all nodes within one connected component.

- This concept is not yet implemented and it solves understanding about Level Order Traversal.

- It fixes #1028 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code  | Output     |
|Screenshot (514)| Screenshot (512)|

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@Lakhankumawat @Mrjoy832  any changes required?

**Comment by Mrjoy832** [comment]
> @Lakhankumawat @Mrjoy832 any changes required?

image

**Comment by Mrjoy832** [comment]
> @Mrjoy832 can you preview readme file.. I think it's fixed

Nice

**Comment by mdnazisharman2803** [comment]
Screenshot_2022-04-11-17-32-56-106_com android chrome

**Comment by mdnazisharman2803** [comment]
Thank you

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

**Pull request merged**
