### PR TITLE
Templates in C++

### PR DESCRIPTION
**Pull request by shr-code**
## Related Issue
- T-Templates in C++( #1220  )

## Proposed Changes
- Explained about templates
- Types of template implementation
- Added syntax of function and class templates

## Additional Info
- Templates are powerful feature of C++. I want to add a folder T-Templates where I have discussed about Templates, its implementation types and their syntaxes.  

## Checklist

- [x] ✅ My code follows the code style of this project.
- [] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by shr-code** [comment]
@Mrjoy832 @aditi944 @Lakhankumawat @siddhi-244 please review this.

**Comment by aditi944** [comment]
Okay

**Comment by shr-code** [comment]
Can you please increase my level too? As most of the contributors have used STL but as far as I have seen no one has mentioned about templates. @aditi944

**Comment by aditi944** [comment]
@Lakhankumawat

**Comment by shr-code** [comment]
Is there any changes to be done? I have previously contributed to this repo. I have read the contributing guidelines and also I have updated my README.md accordingly. @Lakhankumawat

**Comment by shr-code** [comment]
@aditi944 can you approve it?
@miraj0507

**Review by aditi944 — APPROVED** [review]

**Comment by aditi944** [comment]
done

**Comment by shr-code** [comment]
@Lakhankumawat Aditi has approved it! Now it can be merged, right?

**Comment by shr-code** [comment]
@Lakhankumawat @aditi944 ???

**Review by Lakhankumawat — APPROVED** [review]
🎉✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @shr-code code ,

**Pull request merged**
