### PR TITLE
Reverse a Stack using Recursion

### PR DESCRIPTION
**Pull request by nishkarsh800**
## Related Issue
- Reverse a Stack (Recursion) #1451

## Proposed Changes
- I have added the following things: -
- Problem Statement
- Examples
- Algorithm
- Code
- Time Complexity & Space Complexity

## Additional Info
[LINK OF THE PROBLEM STATEMENT](#link-of-the-problem-statement)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to reverse a stack using recursion.

I have added the Problem Statement, Examples, an Algorithm on how to approach this problem, a commented Code, and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Recursion i.e. Reverse a Stack and this problem helps in understanding the concept of Recursion in depth.

I coded this problem in VS Code and tested the given problem on the test cases in the range: -1 <= size of the stack <= 10^4
-10^9 <= Each element of the stack <= 10^9.
Sum of N over all test cases doesn't exceeds 10^6
Array may contain duplicate elements. 
And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
|Input : st = {5,6,7,8}|Input : st ={3,2,1,7}|
|image|image|

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Put all into S-Stack

**Comment by Mrjoy832** [comment]
LGTM🌟

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
Congratulations welcome to the team @nishkarsh800 , first contribution ⭐

**Comment by Lakhankumawat** [comment]
@all-contributors please add @nishkarsh800 code ,

**Comment by Lakhankumawat** [comment]
Check out your Name : https://github.com/Lakhankumawat/LearnCPP#contributors-

**Pull request merged**
