### PR TITLE
Iterative merge sort added #121

### PR DESCRIPTION
**Pull request by Rahul2570089**
## Related Issue
- #121 

## Proposed Changes
- Iterative algorithm of merge sort added.

## Additional Info
- Provided gfg link in readme file.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
- It is #121 issue.
- I added the iterative merge sort algorithm in the "mergesort.cpp" file in "S-SortingAlgorithm" folder and also updated readme file with geeksforgeeks link which has little bit different approach than me.
- I tested the algorithm in VS code IDE taking input array as 5,4,3,2,1,9,6,7 and have provided the output.

## Output Screenshots
| Code: |
code
| Output |
output

### CODE REVIEW

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Improve README
For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

**Review by Rahul2570089 — COMMENTED** [review]
I have updated the readme file please verify

**Review by Rahul2570089 — COMMENTED** [review]
I have updated readme file , please verify

**Comment by Rahul2570089** [comment]
Sorry by mistake I committed two review requests.

**Pull request closed without merging**
