### PR TITLE
Issue #1318 resolved: Sort an array in wave form

### PR DESCRIPTION
**Pull request by AastikSharma05**
## Related Issue
- The problem is Given an unsorted array of integers, sort the array into a wave like array. An array ‘arr[0..n-1]’ is sorted in wave form if arr[0] >= arr[1] <= arr[2] >= arr[3] <= arr[4] >= …..
 ( issue number #1318  )
- Added the code implementation of Sort an array in wave form.
- Added the explanation of Sort an array in wave form Problem in the README.md file.

## Proposed Changes
- Added the code of  Sort an array in wave form Problem .
- Added README.md file of Sort an array in wave form Problem with time complexity.

## Additional Info
- This is one of the commonly asked interview questions and the concept of this question helps us to solve many more problems.'
- This code solves an open issue #1318 
- I have tested these changes on VS code using multiple inputs and matched the output with the expected output.
- This change will not affect or create conflict with any other code.
- Time complexity: O(NlogN)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code Snippet  | Readme Snippet     |
| code  |  readme    |

### CODE REVIEW

**Comment by AastikSharma05** [comment]
@Mrjoy832 @siddhi-244 @miraj0507 @vilsi12 please review my pr.

**Review by Mrjoy832 — APPROVED** [review]

**Comment by AastikSharma05** [comment]
@Lakhankumawat  Please if it is possible then please label it as **Level3**

#1326 
https://github.com/Lakhankumawat/LearnCPP/pull/1309
https://github.com/Lakhankumawat/LearnCPP/pull/1286
https://github.com/Lakhankumawat/LearnCPP/pull/1275
https://github.com/Lakhankumawat/LearnCPP/pull/490
https://github.com/Lakhankumawat/LearnCPP/pull/465
https://github.com/Lakhankumawat/LearnCPP/pull/369

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
https://www.geeksforgeeks.org/sort-array-wave-form-2/ Level3 , really you think so , please see some level3 prs in development based repos when the contribution efforts are too much then it is valid for level3

**Pull request merged**
