### PR TITLE
Added Bisection Method File along with readme.md

### PR DESCRIPTION
**Pull request by riyasingh240601**
## Related Issue
code for bisection method. #1446

## Proposed Changes
- Added a Bisection Method File along with readme.md 

## Additional Info
I'm a GSSoC'22 contributor. I've made the required changes. Kindly merge it to the main.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Screenshot #1    
 code 
 Screenshot (150)

  Screenshot #2  
continuation of previous code   
  Screenshot (149)     

Screenshot #3
Output 
Screenshot (150)

### CODE REVIEW

**Comment by aditi944** [comment]
Please add the required screenshots

**Comment by riyasingh240601** [comment]
Added Screenshots of Code + Outputs

**Comment by aditi944** [comment]
Add the title of the images too. Please read the guidelines properly

**Comment by aditi944** [comment]
It is not in the correct format. Have a look again

**Comment by riyasingh240601** [comment]
is it ok now @aditi944

**Comment by aditi944** [comment]
The title should be just above the image. Pls correct the format. rest looks good

**Comment by riyasingh240601** [comment]
corrected it @aditi944

**Comment by aditi944** [comment]
Can you add a separate screenshot of the output and give it the heading "output"?  Pls do the same in other pr

**Comment by riyasingh240601** [comment]
@aditi944 added a separate screenshot for the output.

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]

**Comment by Lakhankumawat** [comment]
### Major issues with this PR 
1. Too many commits ❌❌
2. Why primeSum is deleted and other README like readme of AdvancedDataStructure is Modified 
image

3. Not followed proper README guidelines .
4. File naming conventions are not seen i guess .
image

**Pull request closed without merging**
