### PR TITLE
Doubly linked list

### LINKED ISSUE #606: Doubly linked list
### Description

I want to add doubly linked list since it's absent in the Linked list folder 

### Domain

Data Structure

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

### PR DESCRIPTION
**Pull request by Sukriti-m**
## Related Issue
-Implementation Of Doubly Linked List (Closes #606   )

## Proposed Changes
- Implementation Of Doubly Linked List performing different operations such as insertion, deletion and display of elements in a list.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

1. Implementation of doubly Linked List performing different operations such as insertion, deletion and display of elements in a list.
2. I have created 3 functions:

- Insert() -To insert elements

- Delete() -To delete elements

- Display() -To display elements

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Test Case 1  | Test Case 2   |
| 
dll
 |       
dll1
         |
Please review this PR.

### CODE REVIEW

**Comment by Sukriti-m** [comment]
> There is no readme !

I have added about the Doubly linked list in the README.md file

**Comment by Sukriti-m** [comment]
@siddhi-244 Please review it now.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Sukriti-m code ,

**Pull request merged**
