### PR TITLE
Pow (x,n): Divide-and-conquer # 1493

### PR DESCRIPTION
**Pull request by PrashantVIT1**
## Related Issues
-  Pow (x, n): Divide-and-conquer # 1493

## Proposed Changes
-  updated the readme file

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1 |  Screenshot #2 |
| ----------- | ----------- |
|  Result 1 |  Result 2  |
| image | image|

### CODE REVIEW

**Comment by PrashantVIT1** [comment]
please add your suggestions if any other issues are also pending.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
## LGTM ✨🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @PrashantVIT1 code ,

**Pull request merged**
