### PR TITLE
Added Vertical Traversal of a tree

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR for the issue Vertical traversal of a tree #1192.
My code works in the following way, Please refer to screenshots
Vertical traversal of a tree-2

Vertical traversal of a tree

### CODE REVIEW

**Comment by eswarbhageerath** [comment]
@Lakhankumawat Please review my PR

**Comment by Mrjoy832** [comment]
Follow guidelines to make PR

**Comment by Mrjoy832** [comment]
1. Short Description or CheckLists

Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.




For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.





Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

**Comment by Mrjoy832** [comment]
Add readme  with cpp file to demonstrate the problems

**Comment by eswarbhageerath** [comment]
Ok sir

**Pull request closed without merging**
