### PR TITLE
Binary Tree

### PR DESCRIPTION
**Pull request by Purvak-10**
## Binary Tree details 
- Binary Tree details, issue number #302 

## I added algorithms to find:
- Number of leaf nodes in the binary tree
- Number of Internal nodes in the binary tree
- Total number of nodes in the binary tree
- Height of the binary tree

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Contribute only one file at a time , delete rest of those and create a new PR for those it will be better for you only if you follow this approach beacuase more number of valid pr's will give you more points 

Keep Height of Binary Tree and delete REST

**Comment by Lakhankumawat** [comment]
Complete the checks which apply to you and Give Star to the REPO

**Comment by Purvak-10** [comment]
Sir, should create another pull request for other algorithms? @Lakhankumawat

**Comment by miraj0507** [comment]
Hello, kindly don't hardcode the input part, create a user input for that portion

**Comment by Purvak-10** [comment]
> Hello, kindly don't hardcode the input part, create a user input for that portion

Sir, I have edited the code with user input, please take a look.

**Pull request closed without merging**
