### PR TITLE
Finding all subarrays 

### PR DESCRIPTION
**Pull request by aikanshi-1234**
## Related Issue
- #208 
## Proposed Changes
- Change 1
image

- Change 2
image

## Additional Info
- code editor used-Atom
## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

> An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array (generally denoted by the name of the array). The base value is index 0 and the difference between the two indexes is the offset.

**Proposed Changes**
> Code added and updated the readme in which time complexity  as well as space complexity is mentioned  .

**Why is this change required? What problem does it solve?**
> Since there was no issue based on this problem

**Include details of your testing environment, and the tests you ran to**
> code editor used -Atom, Pycharm
> compiler used -MingW

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| code view  | directory view     |
| image
  | image
     |

### CODE REVIEW

**Review by Lakhankumawat — APPROVED** [review]
LGTM

**Comment by Lakhankumawat** [comment]
In the README remove the two screen shots you have to paste the screenshots of working algorithm other than code or output screenshot

**Comment by miraj0507** [comment]
Kindly, remove the code snippet screenshot from the readme, and promise some idea about the working of it.

**Comment by miraj0507** [comment]
Any further updates?

**Comment by miraj0507** [comment]
Due to inactivity i need to close this

**Pull request closed without merging**
