### PR TITLE
Knapsack with duplicate items

### PR DESCRIPTION
**Pull request by Shweta2024**
## Related Issue
- Knapsack with Duplicate Items #1226

## Proposed Changes

I have added the following things: -

- Problem Statement
- Examples
- Explanation
- Pseudo Code
- Code
- Time Complexity & Space Complexity

## Additional Info
- [Link of the Problem Statement](https://practice.geeksforgeeks.org/problems/knapsack-with-duplicate-items4201/1/#)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to find the maximum profit provided that we do not exceed the knapsack capacity and an item can be taken any number of times.

I have added the Problem Statement, Examples, an Explanation on how to approach this problem, a commented Code, Pseudo Code,  and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Dynamic Programming i.e. Knapsack with Duplicate Items and this problem helps in understanding the concept of Dynamic Programming.

I coded this problem in VS Code and tested the given problem on the test cases in the range 1 ≤ N, W ≤ 1000,1 ≤ val[i], wt[i] ≤ 100. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Input: N = 2, W = 3 | Input: N = 4, W = 8  |
|image| image |

### CODE REVIEW

**Comment by Mrjoy832** [comment]
rename **Explanation** to **Algorithm** in readme

**Comment by Shweta2024** [comment]
> 



> rename **Explanation** to **Algorithm** in readme

The requested changes have been made. Please review my PR.

**Comment by Mrjoy832** [comment]
LGTM🌟

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🎉✨

**Pull request merged**
