### PR TITLE
Word Wrap Problem

### PR DESCRIPTION
**Pull request by Purvak-10**
## Related Issue
- Word Wrap Problem, issue no. #1387

## Proposed Changes
- Given ‘n’ words of various lengths, and a limit on the number of characters that can be put in one line. Assume each word has length less than the width of line. You have to arrange these given words in line.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
- Let take an array A={aaa, bbb, cc, dddd} and length of line=6.

wwp
    
w_w_p

### CODE REVIEW

**Comment by Purvak-10** [comment]
@Mrjoy832 Please check my pr for issue no. #1387

**Review by Mrjoy832 — CHANGES_REQUESTED** [review]

**Comment by Mrjoy832** [comment]
Put ticks on proper boxes

**Comment by Purvak-10** [comment]
> Put ticks on proper boxes

@Mrjoy832 which box should i tick? I think i tick accordingly.

**Comment by Purvak-10** [comment]
> > > Put ticks on proper boxes
> > 
> > 
> > @Mrjoy832 which box should i tick? I think i tick accordingly.
> 
> I closed my laptop and on my bed 😂😂please check Amy merged PR

**Comment by Purvak-10** [comment]
> > > > Put ticks on proper boxes
> > > 
> > > 
> > > @Mrjoy832 which box should i tick? I think i tick accordingly.
> > 
> > 
> > I closed my laptop and on my bed 😂😂please check Amy merged PR

@Mrjoy832 Can you please tell me what do you by "Amy Merged PR", i don't get it?
and by mistake i closed my PR can you please also tell how to reopen "i by mistake clicked on closed without comment".

**Comment by Purvak-10** [comment]
> > > > > Put ticks on proper boxes
> > > > 
> > > > 
> > > > @Mrjoy832 which box should i tick? I think i tick accordingly.
> > > 
> > > 
> > > I closed my laptop and on my bed 😂😂please check Amy merged PR
> 
> @Mrjoy832 Sorry for this late, Can you please tell me what do you by "Amy Merged PR", i don't get it?

**Comment by Mrjoy832** [comment]
Put tick on 2nd box

**Review by Mrjoy832 — APPROVED** [review]

**Comment by Purvak-10** [comment]
> Put tick on 2nd box

@Mrjoy832 Is there any further process to get my PR merged?

**Comment by Mrjoy832** [comment]
LGTM🌟

**Comment by Purvak-10** [comment]
@Mrjoy832 Out of this pr, a doubt, How many PR's should get merged to get official certificate from GSSOC, because from next week i am having my exams?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 Out of this pr, a doubt, How many PR's should get merged to get official certificate from GSSOC, because from next week i am having my exams?

I think 60 points ...but not 100% sure

**Pull request merged**
