### PR TITLE
Linear Recursion

### PR DESCRIPTION
**Pull request by i-am-aisha**
## Related Issue
#1386

## Proposed Changes
- Create LinearRecursion.cpp file with proper code of linear recursion with proper comments and most understandable way.
- Update Readme accordingly.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Code image
Screenshot (32)
Screenshot (33)

Input image
Screenshot (30)

Output Image
Screenshot (31)

### CODE REVIEW

**Comment by i-am-aisha** [comment]
@aditi944 please review my PR

**Comment by aditi944** [comment]
Please add proper comments to the code

**Comment by i-am-aisha** [comment]
@aditi944  updated please check

**Comment by i-am-aisha** [comment]
@aditi944 please check my pr its been so long

**Comment by i-am-aisha** [comment]
@aditi944 when you will check my pr ? please check it its been 15 days when create this

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🎉✨

**Pull request merged**
