### PR TITLE
LCA of  a binary tree

### PR DESCRIPTION
**Pull request by stutimohta20**
## Related Issue
- #268 

## Proposed Changes
- Added a code to find the lca of a binary tree
- updated the readme file

## Additional Info
-  This code helps in finding the Lowest Common Ancestor of a Binary Tree
- I have tested these changes on VS code and online compiler gdb and matched the output with the expected output.
- This change will not affect or create conflict with any other code.
- Time Complexity - O(n)
Space Complexity - O(1)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Code Screenshot #1| Output Screenshot #1|
| ----------- | ----------- |
||  |

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.



///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by siddhi-244** [comment]
@stutimohta20  you haven't starred the repo !

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Can you explain the approach in detail ?

**Comment by stutimohta20** [comment]
Sorry for the delay , was caught up in something 
please merge this @siddhi-244

**Comment by stutimohta20** [comment]
Please review my PR @Lakhankumawat @siddhi-244

**Comment by stutimohta20** [comment]
@siddhi-244 @Lakhankumawat I have created another issue and am not being able to contribute to it,since this is not merged

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You haven't taken the trees as input !

**Comment by stutimohta20** [comment]
I tried but i coouldnt figure ut how to do it

**Comment by siddhi-244** [comment]
> I tried but i coould nt figure out how to do it @siddhi-244

Take help from the internet! There are many resources to help you !

**Comment by siddhi-244** [comment]
Any updates ?

**Pull request closed without merging**
