### PR TITLE
Just added a few algorithms (of the operations)in Stack section and it's implementation altogether.

### PR DESCRIPTION
**Pull request by rutujaingole**
I somehow had changed the commit message under the Sorting file too and so had to make a few minor changes to restore it again.

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
1. Great , But refactor your code there are bunch of repetitive statements and functions in implementation file
 [Check out my code here ](https://onlinegdb.com/HkQDFMbXd) you can do like this .

2. Rename _Implement Stack_ to **StacksWithoutSTL** better to relate with the file name.
3. Rename  _Operations Algo_ to **Stack Operations**  

Rest everything is okay 

After this requested changes i m good to go with the merge .

**Comment by rutujaingole** [comment]
Made the desired changes, in case of any further improvement, suggestions or guidance will be appreciated.

**Comment by Lakhankumawat** [comment]
👍

**Comment by Lakhankumawat** [comment]
@all-contributors please add @rutujaingole  code

**Comment by Lakhankumawat** [comment]
@all-contributors please add @rutujaingole  code

**Pull request merged**
