### PR TITLE
Prefix Sum in 1-D array#257

### PR DESCRIPTION
**Pull request by ShruthiKartik**
## Related Issue
- Prefix Sum in 1-D array#257
- Added the code of implementation of Prefix Sum in a 1-D array .
- Added the explanation of Prefix Sum technique used in 1-D array in README.md file.

## Proposed Changes
- Change 1 Added code of Prefix Sum with time and space complexity along with comments
- Change 2 Added the README.md of Prefix Sum in 1-D array

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Test Case 1
image

Test Case 2
image

### CODE REVIEW

**Review by Lakhankumawat — COMMENTED** [review]
Good Work

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by siddhi-244** [comment]
@ShruthiKartik  you havent starred the repo

**Comment by ShruthiKartik** [comment]
@siddhi-244 how to star the repo? And, pls tell me what are the incomplete checks?

**Comment by siddhi-244** [comment]
> @siddhi-244 how to star the repo? And, pls tell me what are the incomplete checks?

You can see the star option to the left of fork, just click on that !

**Comment by ShruthiKartik** [comment]
@siddhi-244 Done!

**Comment by siddhi-244** [comment]
> @siddhi-244 Done!

LGTM !

**Comment by ShruthiKartik** [comment]
@siddhi-244 There is a tag of incomplete checks. So, can u pls tell me what are those incomplete checks so that I can do the changes.

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯

**Comment by Lakhankumawat** [comment]
@all-contributors please add @ShruthiKartik  code ,

**Pull request merged**
