### PR TITLE
Searching Algorithm - Sequential and Binary Search

### PR DESCRIPTION
**Pull request by janhavikale06**
## Related Issue
#727 

## Proposed Changes
- Added a code for #727 

## Additional Info
- Sequential Search is used for unsorted and unordered small list of elements.
- It has a very simple implementation.
- Best-case complexity is O(1) where the element is found at the first index.
- Worst-case complexity is O(n) where the element is found at the end of array or element is not present in the array.
- Space complexity : O(1)

- Binary Search is an efficient algorithm for finding an element from a sorted array.
- It is used to narrow the search. For large lists of data, it works significantly better than Sequential Search.
- Time complexity : O(log n)
- Space complexity : O(1)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
LinearSearch
BinarySearch

### CODE REVIEW

**Comment by janhavikale06** [comment]
Hey @Lakhankumawat , can you please check my PR ?

**Comment by janhavikale06** [comment]
Hey @Lakhankumawat , can you please check my issue it has been so many days since I've created it?

**Comment by Mrjoy832** [comment]
Put tick on required proper points

**Comment by Mrjoy832** [comment]
Wrong Files Changed..readme missing

**Comment by janhavikale06** [comment]
> 1.Too many commits 2. Nothing Changed as per given instruction **Create Fresh PR following guidelines and less commits**

Okay will do it.

**Pull request closed without merging**
