### PR TITLE
add new file Morris_Traversal in T-TreeTraversal

### PR DESCRIPTION
**Pull request by adi2002vicky**
## Related Issue
I add new file Morris_Traversal in T-TreeTraversal
## Proposed Changes
- Change 1
- Chnage 2

## Additional Info
ADD NEW README.md FILE

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Morris traversal is a traversal technique which uses the concept of threaded binary tree and helps to traversal any binary tree without recursion and without using stack (any additional storage). In this PR we discuss Morris Traversal for inorder binary tree traversal.

traverse binary tree without recursion and without stack

Test Configuration:
Operating system: window
Version:10
Text-editors used : vs code

- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| #Screenshot 1|
input output 1
Screenshot 2022-03-08 172342
Screenshot 2022-03-08 172427
| Screenshot #2  |
input output 2
Screenshot 2022-03-03 202230
Screenshot 2022-03-03 202257

### CODE REVIEW

**Comment by adi2002vicky** [comment]
i am gssoc 2022 contributor pls assign me sir and merge my pr after reviewing

**Comment by Lakhankumawat** [comment]
///-----------------CheckList-------------------------///
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)



For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
you haven't added readme and there is an extra exe file which is not needed!

**Comment by adi2002vicky** [comment]
@siddhi-244  mam i dlt extra files and  i added subfiles in side tree traversal so i thik not need readme.md pls check because inorder preorder postorder traversal readme.md files are not present but if you want this file i add this pls check again mam

**Comment by siddhi-244** [comment]
> @siddhi-244 mam i dlt extra files and i added subfiles in side tree traversal so i thik not need readme.md pls check because inorder preorder postorder traversal readme.md files are not present but if you want this file i add this pls check again mam

Heyy,readme is needed because the explanation of the algo/problem lies in the readme.

**Comment by Lakhankumawat** [comment]
@adi2002vicky make sure you follow  the guidelines mentioned above .

**Comment by Lakhankumawat** [comment]
1. Star the repo
2. Paste some screen shots in PR description of your PR .
3. Expain the working of morris sort in PR Description
You need to follow particular guidelines for your README , please follow

these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms)
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)
for more please go through these [here](https://youtu.be/7UgC3HDETRA)


We will approach this PR again with in a 2-3 days , if there are not required changes we will close it , thanks .

**Comment by adi2002vicky** [comment]
> @adi2002vicky make sure you follow the guidelines mentioned above .

okk sir

**Comment by adi2002vicky** [comment]
pls again check pr sir

**Comment by siddhi-244** [comment]
You haven't starred the repo yet !

**Comment by adi2002vicky** [comment]
> You haven't starred the repo yet !

Thanks for your concern, I have starred it! 🙃

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Follow the readme guidelines.  Add time and space complexity in the readme. Try to explain the approach!

**Comment by adi2002vicky** [comment]
> Follow the readme guidelines. Add time and space complexity in the readme. Try to explain the approach!
check again mam @siddhi-244

**Comment by Lakhankumawat** [comment]
Add Comments in your code follow this https://github.com/Lakhankumawat/LearnCPP#algorithms and then i'll merge your PR thanks

**Comment by adi2002vicky** [comment]
@Lakhankumawat sir pls check again

**Comment by Lakhankumawat** [comment]
LGTM 💯

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯

**Comment by Lakhankumawat** [comment]
@all-contributors please add @adi2002vicky  code ,

**Pull request merged**
