### PR TITLE
Lowercase to uppercase

### PR DESCRIPTION
**Pull request by ujjwalban**
## Related Issue
#24

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Okay seems all good to me

Just final step instead of having X in checkboxes just tick the required above and it will be merged

**Comment by ujjwalban** [comment]
Done bhaiya..
lets do it..
done checklist.

**Comment by Lakhankumawat** [comment]
Please star the repo ......

**Comment by Lakhankumawat** [comment]
https://github.com/all-contributors please add @ujjwalban code

**Comment by Lakhankumawat** [comment]
https://github.com/all-contributors please add @n4i9kita maintenance , ideas

**Comment by Lakhankumawat** [comment]
@all-contributors please add @ujjwalban  code

**Comment by Lakhankumawat** [comment]
@all-contributors please add @ujjwalban  code

**Pull request merged**
