### PR TITLE
added LongestCommonSubsequence.cpp in dynamic programming and updated…

### PR DESCRIPTION
**Pull request by sebinfrancis7**
… README.md

## Related Issue
- Added Longest Common Subsequence in D-Dynamic Programming and updated the README.md with the explanation of the mentioned problem. (Issue : #64 )

## Proposed Changes
- Added Longest Common Subsequence problem to Dynamic Programming.
- Updated README.md

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Output - 1 for Longest Common Subsequence  | Output - 2 for Longest Common Subsequence     |
|image|image |

### CODE REVIEW

**Comment by sebinfrancis7** [comment]
@Lakhankumawat can you please check and merge this PR as part of GSSoC 2022.

**Comment by sebinfrancis7** [comment]
@Lakhankumawat

**Comment by sebinfrancis7** [comment]
@Lakhankumawat any updates?

**Comment by miraj0507** [comment]
All checks passed, code seems to work fine, can you make your description a bit  elaborate and we are good to go .

**Comment by sebinfrancis7** [comment]
@miraj0507 description in the README.md ?

**Comment by sebinfrancis7** [comment]
@miraj0507 can you please clarify.

**Comment by n4i9kita** [comment]
Hey @sebinfrancis7.

Could you please write the readme in your own language rather than directly copying from the source?

**Comment by sebinfrancis7** [comment]
@n4i9kita sure

**Comment by miraj0507** [comment]
The code and the readme look good to me. We can proceed further.

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🌟💯 
Nice Work @sebinfrancis7  keep contributing 

 You can Improve your contribution further and then your code will be directly merged by me if everything looks okay > Tag me on discord if you have made any other good Prs like this , but make sure they follow all the guidelines and are not incomplete .

**Comment by Lakhankumawat** [comment]
@all-contributors please add @sebinfrancis7 code ,

**Comment by sebinfrancis7** [comment]
> LGTM 🌟💯 
> Nice Work @sebinfrancis7  keep contributing 
> 
>  You can Improve your contribution further and then your code will be directly merged by me if everything looks okay > Tag me on discord if you have made any other good Prs like this , but make sure they follow all the guidelines and are not incomplete .

Sure @Lakhankumawat

**Pull request merged**
