### PR TITLE
Intersection of Sets

### PR DESCRIPTION
**Pull request by Pranshu321**
## Related Issue
- #1469 

## Proposed Changes
- Cpp file added
- readme file added

## Additional Info
**In this, I Have explained all about the intersection:**
- What is the meaning of the intersection of sets?
- properties of intersection in sets? 
- working example image

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

The intersection of two sets A and B is the set of all elements common in both sets as identical in both A and B set, The intersection of A and B is denoted as `A ∩ B`.

#1469 

Any GCC compiler

- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| Code  Output| 
image

### CODE REVIEW

**Comment by aditi944** [comment]
Please add screenshots of code with proper comments

**Comment by Pranshu321** [comment]
> of code with proper

ScreenShots in the readme or any other place and I have given well-defined comments in the CPP file @aditi944 .

**Comment by aditi944** [comment]
You have to add screenshots in the readme

**Comment by Pranshu321** [comment]
> You have to add screenshots in the readme

Screenshots added @aditi944  now check readme.

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 💎

**Pull request merged**
