### PR TITLE
added 2 pointer section

### PR DESCRIPTION
**Pull request by Supratim2000**
Searching in the repository I found that there was no 2 pointer section. So I have added this section to complete this repository with various algorithms.

### CODE REVIEW

**Comment by Supratim2000** [comment]
2 pointer section added

**Comment by Lakhankumawat** [comment]
Please follow this steps 
1. Delete your current fork
2. clone project again and add this file in [P-Problem Statements & Solution/1-Level 1](https://github.com/Lakhankumawat/LearnCPP/tree/main/P-Problem%20Statements%20%26%20Solution/1-Level%201)
3. Follow the PR template and create pull request.

Thanks Happy Coding !

**Comment by Lakhankumawat** [comment]
> Please follow this steps
> 
> 1. Delete your current fork
> 2. clone project again and add this file in [P-Problem Statements & Solution/1-Level 1](https://github.com/Lakhankumawat/LearnCPP/tree/main/P-Problem%20Statements%20%26%20Solution/1-Level%201)
> 3. Follow the PR template and create pull request.
> 
> Thanks Happy Coding !

Cause this program is a problem statement with solution , it is not STL quicklook or algorithm , we want to work tree clean that's why

**Comment by Supratim2000** [comment]
Ok wait for a second

**Comment by Supratim2000** [comment]
Will you accept my PR?

**Pull request closed without merging**
