### PR TITLE
added a Multithread merge sort cpp file

### PR DESCRIPTION
**Pull request by adham-nasr**
### Related issue
-Issue:  #132

**Proposed Changes**
     
       added a multi-threading merge sort algorithm

**Checklist**
> * [x] ✅ My code follows the code style of this project.
> * [ ] My change  requires a change to the documentation
> * [ ] I have updated the documentation accordingly
> * [x] I have read the [CONTRIBUTING](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
> * [x]  🚩 All new and existing tests passed.
> * [x]  🌟 ed the repo

### Output Screenshots:

**Code :**

scre1

**Input test case :**

scre2

**Output sample :**

scre3

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Let me show you how to check the check list , there should be no space inside brackets like [x]

[x]
Checklist
Or you can just check them from outside without doing any of these

 ✨ I have added tests to cover my changes.
 🚩 All new and existing tests passed.
 🌟 ed the repo
Starr the repo if you haven't
Have you watched this [video](https://youtu.be/kIFwqp9B7pQ)

**Comment by Lakhankumawat** [comment]
Hey @adham-nasr  , make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

**Comment by Lakhankumawat** [comment]
@adham-nasr  if you are still active with the PR then comment and do the mentioned changes above and we will remove the hold label , otherwise this pr will be closed automatically if you remain inactive for more number of days

**Comment by adham-nasr** [comment]
> Let me show you how to check the check list , there should be no space inside brackets like [x] `[x]`
> 

> 
> 1. Starr the repo if you haven't !
> 2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?

**Comment by adham-nasr** [comment]
> @adham-nasr if you are still active with the PR then comment and do the mentioned changes above and we will remove the hold label, otherwise this pr will be closed automatically if you remain inactive for more number of days

Yes I'm active and I did the mentioned changes above, it should be correct by now

**Comment by aditi944** [comment]
closed

**Pull request closed without merging**
