### PR TITLE
Added Shell Sort Algorithm

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
## Related Issue
- Shell Sort (#1047) 

Shell sort is a generalized version of the insertion sort algorithm. It first sorts elements that are far apart from each other and successively reduces the interval between the elements to be sorted.

## Proposed Changes
- Added ShellSort.cpp
- Made corresponding changes in the README. 

## Checklist

- [X] ✅ My code follows the code style of this project.
- [X] 📝 My change requires a change to the README.
- [X] 🎀 I have updated the README accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [X] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Screenshot_2022-04-04-16-43-11-138_com android chrome
Screenshot_2022-04-04-16-43-18-769_com android chrome

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
Hi @Lakhankumawat @siddhi-244 kindly review my PR and let me know if any change is required

**Review by Lakhankumawat — COMMENTED** [review]
Implementation of Shell Sort #329 Duplicate 😥

**Comment by Lakhankumawat** [comment]
Your contribution is good but your pr will be on hold if the earlier prs are inactive .

**Comment by Lakhankumawat** [comment]
closed #1047

**Comment by abhilipsasahoo03** [comment]
> Your contribution is good but your pr will be on hold and closed if the earlier prs are inactive , your pr will be reopened reviewed and merged .

@Lakhankumawat I'm sorry the other ShellSort PR wasn't merged and it was opened 1 month ago so I had missed out on that.

Just a trivial question.

Since I have made a rather detailed README and noticed that the other PR hasn't, any chances the other PR wouldn't get merged, and mine would be reopened and merged instead? Or is it closed permanently?

Please let me know.

**Pull request closed without merging**
