### PR TITLE
Subsequence K Sum

### PR DESCRIPTION
**Pull request by LakshayN**
## Related Issue
- Mention issue for which this pull request is a part of (#115  )

## Proposed Changes
- Added subsequence with K sum problem using recursion

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| 
image
      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Comment by LakshayN** [comment]
> Add table of contents in readme!

@siddhi-244 I've already added that

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]

**Comment by LakshayN** [comment]
@Lakhankumawat I've added the photo of algorithm in readme

**Review by Lakhankumawat — APPROVED** [review]
## LGTM ✨🎉

Good Contribution @LakshayN

**Comment by Lakhankumawat** [comment]
Keep Learning ✨
Keep Growing 🌱

**Comment by Lakhankumawat** [comment]
@all-contributors please add @LakshayN code ,

**Pull request merged**
