### PR TITLE
Diameter of The Binary-Tree

### PR DESCRIPTION
**Pull request by Bhavneet345**
## Related Issue
-  #353, 
- Problem Statement - You are given a Binary Tree. You are supposed to return the length of the diameter of the tree. The diameter of a binary tree is the length of the longest path between any two end nodes in a tree.

## Proposed Changes
- Added code of the Diameter of the Binary Tree.
- Added README.md file of the problem with time and space complexity.
- Added the problem statement of the code.

## Additional Info
- Used the pair class of C++ to compute the diameter and height of the tree simultaneously.
- Implemented Object Oriented programming logic to represent the individual nodes of the tree.
- Provided the code with appropriate comments for efficient reading.
- This code solves an open issue https://github.com/Lakhankumawat/LearnCPP/issues/353
- I have tested these changes on VS code using multiple inputs and matched the output with the expected output.
- This change will not affect or create conflict with any other code
- Time Complexity - O(N), N - Number of nodes in a Binary-Tree.
- Space Complexity - O(H), H - Height of the Binary-Tree.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1 |  Screenshot #2  |
| ----------- | ----------- |
| INPUT FORMAT | OUTPUT 1  |
|  Screenshot 2022-03-09 at 11 06 18 AM| Screenshot 2022-03-09 at 11 07 15 AM  |

### CODE REVIEW

**Comment by Bhavneet345** [comment]
Pls review my pull request @iamgunjan @miraj0507 @Lakhankumawat

**Comment by Bhavneet345** [comment]
@Lakhankumawat @iamgunjan @miraj0507 what else do I need to add, kindly tell me

**Comment by Bhavneet345** [comment]
@Lakhankumawat @iamgunjan @miraj0507 please review once I have made the changes, if not met your requirements please tell me what else do I need to add.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Follow the readme guidelines and instead of adding code in readme, you can add the algorithm or approach!

**Comment by Bhavneet345** [comment]
Thank you so much @siddhi-244 I will definitely make the changes accordingly

**Comment by Bhavneet345** [comment]
@siddhi-244 ma'am I have made the changes as per your requirements in the README.md please review them once.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯🌟 

Great work @Bhavneet345  , keep contributing 🌟🌟

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Bhavneet345 code ,

**Pull request merged**
