### PR TITLE
trapping water problem added with updated ReadMe file

### PR DESCRIPTION
**Pull request by shubhamlakheraa**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )
 Trapping Water with optimized solution(#110)

## Proposed Changes
- Change 1
- Added Trapping Water Problem with Optimized solution.
- Change 2
- Updated ReadMe file accordingly.

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Problem Statement & Solution |ReadMe File  |
| 
Screenshot (3)
  | 
Screenshot (4)
  |

### CODE REVIEW

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Add contents to your README

**Comment by Lakhankumawat** [comment]
Please complete the cheklist

**Comment by Lakhankumawat** [comment]
Read contributing steps before creating Pr https://github.com/Lakhankumawat/LearnCPP#read-the-following-steps-before-contributing

**Comment by shubhamlakheraa** [comment]
Completed the checklist as well added the content to the readMe file.

**Pull request closed without merging**
