### PR TITLE
Added a new Problem convert 24hr clock to 12hr clock with detailed explanation and code

### PR DESCRIPTION
**Pull request by mugdhaPandey**
## Related Issue
- Given a time in 24 hr format(military format), convert it to 12 hr format. (#1310 )

## Proposed Changes
- Added a new problem statement with detailed explanation and code

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by mugdhaPandey** [comment]
can anyone please review my PR?

**Comment by siddhi-244** [comment]
Where is the readme ?

**Comment by mugdhaPandey** [comment]
Sorry for that. I will add it as soon as possible.

Thanks

**Comment by mugdhaPandey** [comment]
Kindly check the updated PR @siddhi-244

**Comment by siddhi-244** [comment]
Follow the readme guidelines. 
1. The question is missing.
2. The working image is also missing

**Comment by mugdhaPandey** [comment]
@siddhi-244 Please verify

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
## LGTM ✨🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @mugdhaPandey code ,

**Pull request merged**
