### PR TITLE
Implementation of threaded binary tree

### PR DESCRIPTION
**Pull request by anjaligautam13023**
## Related Issue
#328 

## Proposed Changes
- Problem statement
- Explanation
- Code
- Screenshot

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Implementation of Threaded Binary Tree

In the linked list representation of binary tree, more than half of _link_ field contain _null_ value which results in wastage of storage space.
So  in order to effectively manage space , we use a method called threading ,where all null links are replaced with special link called thread . Each node in a threaded binary tree either contain a link to its child or thread to other node.

I have tested the given problem on the various test cases and it is working fine.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Insertion and Traversal of node  | Deletion of node     |
|screenshot  | 
|capture2     |

### CODE REVIEW

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Nothing inside cpp file no README please add contents to your cpp file and README

**Comment by Lakhankumawat** [comment]
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.



///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

## 1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by anjaligautam13023** [comment]
I have done all required changes.

**Comment by miraj0507** [comment]
That's a good implementation of the code , @Lakhankumawat looks good to me , passing it on to @n4i9kita

**Comment by anjaligautam13023** [comment]
Conflict resolved.

**Pull request closed without merging**
