### PR TITLE
Added Dijkstras Algorithm using Priority Queue in CPP

### PR DESCRIPTION
**Pull request by maheshdbabar9340**
## Related Issue
- Issue number #1073 

## Proposed Changes
- Addd CPP code for Dijkstras Algorithm using Priority Queue

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1      |  |
| ----------- | ----------- |
| Output for the given code  |      |
| image |      |

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Why 3 files changed? only add cpp file and update/add readme

**Comment by Mrjoy832** [comment]
Why You chnage the template ...Use proper template given by us

**Comment by maheshdbabar9340** [comment]
> Why 3 files changed? only add cpp file and update/add readme

@Mrjoy832 Now I completed all changes and added only one cpp file and also updated readme.md file. 

Please let me know if any more changes are required . 

Waiting for your response.

Thank You.

**Comment by maheshdbabar9340** [comment]
> This PR is stale because it has been open 30 days with no activity. Please commit the changes requested or make improvements on the code. Thank you for your contributions!

Completed all changes, Please let me know if any more changes are required .

Waiting for your response.

Thank You.

**Comment by Mrjoy832** [comment]
Resolve conflict

**Comment by maheshdbabar9340** [comment]
> Resolve conflict

image

Resolve conflicts button is not clickable what should i do? @Mrjoy832

**Comment by Mrjoy832** [comment]
> > Resolve conflict
> 
> image
> 
> Resolve conflicts button is not clickable what should i do? @Mrjoy832

You haven't access to the repo..You have to change manually through your forked copy and local repo...**Watch YT video on how to resolve branch conflict**

**Comment by Mrjoy832** [comment]
# Closed

**Pull request closed without merging**
