### PR TITLE
Bipartite Graph

### PR DESCRIPTION
**Pull request by Mrjoy832**
## Related Issue
 #188  

## Proposed Changes
-Added short description about problem statement
-Added code, related input-output

## Checklist

- [X] ✅ My code follows the code style of this project.
- [X] 📝 My change requires a change to the documentation.
- [X] 🎀 I have updated the documentation accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [X] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [X] 🌟 ed the repo

**Solution of issue #188** 
Added brief description about the **bipartite graph** and explained a code using BFS algorithm 
Here I used 2 inputs for the 1st one I show that the graph is bipartite and 2nd input graph is not bipartite
**APPROACH::**
It is possible to test whether a graph is bipartite or not using a BFS Algorithm
There are 2 ways to check for a bipartite graph:
**1. A graph is a bipartite graph if and only if it is colorable by 2 colors only.**
While doing BFS traversal m the given Graph, each node in the BFS tree is given its parent’s opposite color. If there exists an edge connecting the current vertex to a previously colored vertex with the same color, then we can say that the graph is not bipartite.

**2. A graph is a bipartite graph if and only if it  contains an odd cycle(Cycle contains  Odd number of vertices)**
If a graph contains an odd, we cannot divide the graph such that every adjacent vertex has a different color.  If in the BFS, we find an edge, if both of its endpoints are at the same level, then the graph is not Bipartite and an odd-cycle is found. 

**Here in the explanation, we use the 1st approach of the BFS algorithm to check whether a given graph I bipartite or not.**

## Output Screenshots
   

| INPUT-1
bipartite1
 | INPUT-2   |
bipartite2

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Hey @Mrjoy832  you need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by miraj0507** [comment]
Hello, the readme for bipartite code is missing

**Comment by Mrjoy832** [comment]
yeah I will be going to ..as because I have exam tomorrow I am currently
busy little bit

**Comment by Mrjoy832** [comment]
Can @miraj0507  kindly say that with PR how to add or create a readme file..please??

**Comment by Mrjoy832** [comment]
@miraj0507 @n4i9kita  anyone kindly say how to update or add readme with PR ..I cannot understand what to do with Readme file ..I am stucked please help

**Comment by Mrjoy832** [comment]
I will be adding readme file by tomorrow..because I have Hackwithinfy today .. I am a little busy now..kindly don't close my PR

**Comment by miraj0507** [comment]
@Mrjoy832 , The code looks good to me as it would run , but the presentation of the readme can be made better can you please update the headings to make it a bit larger , another mentor would review the same .

**Comment by Mrjoy832** [comment]
@miraj0507  hey I have increased the size of all headings as you said please check

**Comment by miraj0507** [comment]
LGTM , @n4i9kita kindly have a look

**Comment by Mrjoy832** [comment]
> LGTM , @n4i9kita kindly have a look 

@n4i9kita  please check and Merge , I have to start on another issue .

**Comment by miraj0507** [comment]
> > LGTM , @n4i9kita kindly have a look
> 
> @n4i9kita please check and Merge , I have to start on another issue .

you can start on a new issue anytime, one the mentors give a good to go signal it will be merged don't worry

**Comment by Mrjoy832** [comment]
@miraj0507  how my PR is closed without merge?

**Comment by Mrjoy832** [comment]
> @miraj0507  how my PR is closed without merge?

Hey @miraj0507  before you guys merge by mistake I delete the cloned folder from my local machine ..so for that I think PR is closed what should I do now..please say

**Pull request closed without merging**
