### PR TITLE
Reverse a singly Linked List

### PR DESCRIPTION
**Pull request by svenkat19**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )
- Adding a new code for Reversing a linked list in CPP.
https://github.com/Lakhankumawat/LearnCPP/issues/221#issuecomment-1057104563
#221 
## Proposed Changes
- Change 1
- Chnage 2

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Added a CPP program to reverse a linked list.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 

| ----------- | ----------- |
| Reversing a Linked List | 
| image

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Make your issue a descriptive one so it is easy for us
mentors to get hold of your contribution and can guide you for further steps.
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/MRXcoxDillk) , thanks.


///--------------------Pull Requests--------------------///

1. Short Description or CheckLists

Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.


///-----------------CheckList-------------------------///


Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by miraj0507** [comment]
Kindly work on the developments of correcting your readme file as soon as possible

**Comment by svenkat19** [comment]
Yup,on it. I'll make the changes as soon as possible

**Comment by svenkat19** [comment]
Hey. Can you have a look and let me know if I have missed out on anything?

**Comment by n4i9kita** [comment]
Good to go.

**Comment by Lakhankumawat** [comment]
1. Make your PR descriptive 
2. Modify Your README further 
3. 
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by miraj0507** [comment]
Hey kindly change the hard coding part

listl.push(1);
  listl.push(2);
  listl.push(3);
  listl.push(4);
  listl.push(5);
  listl.push(6);
  listl.push(7);
  listl.push(8);
  listl.push(9);
  listl.push(10); to a for loop using user input

**Comment by Lakhankumawat** [comment]
No Response From the contributor of this REPO

**Comment by svenkat19** [comment]
I am working on the read me file. It does take some time and effort to come up with changes, and managing it along with my classes and assignments.

**Comment by Lakhankumawat** [comment]
Ok no problem @svenkat19  you can take your time

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by svenkat19** [comment]
Sure noted. Regarding the ReadMe. How do I gauge how descriptive it must be? Because I can break it down to the simplest layer and show every single iteration. I am new to documentation, so I am not able to make it crisp

**Comment by Lakhankumawat** [comment]
Just follow this https://github.com/Lakhankumawat/LearnCPP/pull/272#issuecomment-1066067397

**Comment by Lakhankumawat** [comment]
This is the third time i am pointing to readme guidelines 
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms)
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
follow these things and then your PR will be merged for sure

1. Add comments to your code regarding working and below code about time and space complexity
2. You still need to modify your README

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
No response from the contributor of this repo !

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯🌟

**Comment by Lakhankumawat** [comment]
@all-contributors please add @svenkat19 code ,

**Pull request merged**
