### PR TITLE
Update README.md of Static implementation of Stack

### PR DESCRIPTION
**Pull request by janhavikale06**
## Related Issue
 #449 

## Proposed Changes
Updated the readme file.

## Additional Info
Stack using Array added to readme file

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Readme |
Stack
Stack 1
Stack 2
Stack 3

### CODE REVIEW

**Comment by siddhi-244** [comment]
Hey your article has plagiarism.  Please rewrite it !

**Comment by janhavikale06** [comment]
> Hey your article has plagiarism. Please rewrite it !

Sorry I've taken some help from google, I'll do it properly.

**Comment by siddhi-244** [comment]
> > Hey your article has plagiarism. Please rewrite it !
> 
> Sorry I've taken some help from google, I'll do it properly.

You havent described your pr ,as well as havent added screenshots of output

**Comment by janhavikale06** [comment]
> > > Hey your article has plagiarism. Please rewrite it !
> > 
> > 
> > Sorry I've taken some help from google, I'll do it properly.
> 
> You havent described your pr ,as well as havent added screenshots of output

Okay , I'll do it

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by siddhi-244** [comment]
Just make ur pr a bit descriptive and check proper tasks!

**Comment by Lakhankumawat** [comment]
@janhavikale06  whatever you are trying to add is already present inside the repo 
Check here https://github.com/janhavikale06/LearnCPP/blob/faba322d4060959448c6035d5c121fd84c298340/S-Stack/StacksWithoutSTL.cpp

this is also a static implementation of stack without STL

**Comment by janhavikale06** [comment]
> @janhavikale06 whatever you are trying to add is already present inside the repo Check here https://github.com/janhavikale06/LearnCPP/blob/faba322d4060959448c6035d5c121fd84c298340/S-Stack/StacksWithoutSTL.cpp
> 
> this is also a static implementation of stack without STL

@Lakhankumawat ,
As you can see the main comment from your side was to add the readme file. Accordingly I've added that , if it's not necessary or if there are any changes required, please tell me.

**Comment by Lakhankumawat** [comment]
You just delete your cpp file and Update readme.md file and do one thing modify the original README in stack after fetch upstream and whatever you feels like is missing there just add those things , **do not rub anything which is existing** cause we can't accept your code and so we will be accepting your PR but for README modifications don't worry .


and No output screenshots in README please
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
1. Uncheck the checks which doesn't applies to you

**Comment by Lakhankumawat** [comment]
@all-contributors please add @janhavikale06  code ,

**Pull request merged**
