### PR TITLE
Longest word in a Sentence (String based question)

### PR DESCRIPTION
**Pull request by Pranshu321**
## Related Issue
- #1149 

## Proposed Changes
- Problem and full explained code is added.

## Additional Info
- Code is explained by comments in a simple manner.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

In this, I have deeply explained how we approach the problem of finding the longest word in a sentence with a useful comment.

Given a string, we have to find the longest word in the input string and then calculate the number of characters in this word and print it.

#1149 

- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1 | 
| ----------- | 
| Code Output| 
image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Readme?

**Comment by Mrjoy832** [comment]
Describe the Problem here also

**Comment by Pranshu321** [comment]
> Describe the Problem here also

> Readme?

Also changes added @Mrjoy832.

**Comment by Pranshu321** [comment]
> image Hey...Can you Fix the heading of 'String COmparison' please fix it like your

@Mrjoy832 Done Sir , Changes requested completed

**Comment by Mrjoy832** [comment]
LGTM🌟

**Review by Lakhankumawat — APPROVED** [review]
### LGTM🎉✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Pranshu321 code ,

**Pull request merged**
