### PR TITLE
Adding the B-Tree algorithm in the T-Tree folder

### PR DESCRIPTION
**Pull request by ayushi1210**
## Related Issue
#51 

## Proposed Changes
Change 1 = Added B-Tree Algorithm with comments and procedure.
Change 2 = Added Readme for B-Tree Algorithm.

## Checklist
- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Screenshot 2022-03-01 at 5 49 07 PM
Test Case

Screenshot 2022-03-01 at 5 44 06 PM
Code Snippet

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Hey @ayushi1210  , make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.


Please make sure your file conventions and extensions are correct .

1. T-Tree/B-BTree/BTrees.cpp

**Comment by Lakhankumawat** [comment]
Let me show you how to check the check list , there should be no space inside brackets like [x]

[x]
Checklist
Or you can just check them from outside without doing any of these

 ✨ I have added tests to cover my changes.
 🚩 All new and existing tests passed.
 🌟 ed the repo
Starr the repo if you haven't
Have you watched this [video](https://youtu.be/kIFwqp9B7pQ)

**Comment by ayushi1210** [comment]
Now I have corrected the checklist and make the readme as per the video and full description of the algorithm I have provided in the readme and the in code as comments.

**Comment by ayushi1210** [comment]
Please review this PR.

**Comment by Mrjoy832** [comment]
image
Remove ticks from these 2

**Comment by Mrjoy832** [comment]
I dont think your cpp file is correct..it has not any cpp extension

**Comment by Mrjoy832** [comment]
Add more points on readme->
- Description
- image
- algo
- time&Space complexity
- Advantages & Disadvantages of using B-Tree

**Comment by ayushi1210** [comment]
I did all the changes suggested and as mentioned in the issue I have to submit c file only.

**Comment by Mrjoy832** [comment]
> I did all the changes suggested and as mentioned in the issue I have to submit c file only.

It's CPP Project add C++ Code

**Comment by ayushi1210** [comment]
All the recommended changes are done.

**Comment by Mrjoy832** [comment]
> All the recommended changes are done.

We cannot take a PR with these much commits ...create a Fresh PR and You have changed 3 files 

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Pull request closed without merging**
