### PR TITLE
Created Right Side View of Binary Tree

### PR DESCRIPTION
**Pull request by R-Ayush777**
Created Right Side View of BT and it's Solution approach to readme file.

## Related Issue
- The problem is Given an a binary tree, write an efficient algorithm to print its right view of Binary Tree.
( issue number https://github.com/Lakhankumawat/LearnCPP/issues/1342 )

## Proposed Changes
- Added the implementation of Right Side View of BT.
- Added README.md file of Problem with time complexity and solution approach.

## Additional Info
- This code solves an open issue https://github.com/Lakhankumawat/LearnCPP/issues/1342
I have tested these changes on VS code using multiple inputs and matched the output with the expected output.
This change will not affect or create conflict with any other code.
Time complexity: O(N)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code Snippet  | Readme Snippet     |
| image  | image     |

### CODE REVIEW

**Comment by R-Ayush777** [comment]
@Lakhankumawat @aditi944 Please review my PR.

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
image

Why is there a modification in Binary Tree README folder 

This is how the README looks like now 

https://github.com/Lakhankumawat/LearnCPP/blob/main/T-Tree/B-BinaryTree/README.md

**Comment by R-Ayush777** [comment]
That confused me as well. When I fork a repo, the changes are shown to me from the beginning (by default), even if I haven't made any modifications. I've tried forking numerous times, but the result stays the same. @Lakhankumawat

**Review by R-Ayush777 — COMMENTED** [review]
Copied original code of Readme file as before.

**Comment by R-Ayush777** [comment]
@Lakhankumawat Review Changes.

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @R-Ayush777 code ,

**Pull request merged**
