### PR TITLE
Added Bucket Sort Algorithm

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )

Fixes issue #1038

## Description
- Bucket Sort is a sorting algorithm that divides the unsorted array elements into several groups called buckets. Each bucket is then sorted by using any of the suitable sorting algorithms (in this case, Insertion Sort) or recursively applying the same bucket algorithm. Finally, the sorted buckets are combined to form a final sorted array.

## Proposed Changes

- Added BucketSort.cpp

- Made corresponding changes to README.md

## Checklist

- [X] ✅ My code follows the code style of this project.
- [X] 📝 My change requires a change to the README.
- [X] 🎀 I have updated the README accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [X] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Screenshot

Screenshot_2022-04-02-12-32-43-949_com android chrome
Screenshot_2022-04-02-12-32-47-770_com android chrome

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
Hi @Lakhankumawat kindly review my PR and let me know if any change is required

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Don't add code in algorithm! Try to explain the steps !

**Comment by abhilipsasahoo03** [comment]
> Don't add code in algorithm! Try to explain the steps !

I'm so sorry, I didn't get you. Can you please expand on that?

**Comment by abhilipsasahoo03** [comment]
> Don't add code in algorithm! Try to explain the steps !

Okay so if I'm not wrong, along with providing the algo, I'm also supposed to explain the steps in the Algorithm section, right? If not, please guide me.

**Comment by siddhi-244** [comment]
> > Don't add code in algorithm! Try to explain the steps !
> 
> Okay so if I'm not wrong, along with providing the algo, I'm also supposed to explain the steps in the Algorithm section, right? If not, please guide me.

Yes

**Comment by abhilipsasahoo03** [comment]
> > > Don't add code in algorithm! Try to explain the steps !
> > 
> > Okay so if I'm not wrong, along with providing the algo, I'm also supposed to explain the steps in the Algorithm section, right? If not, please guide me.
> 
> Yes

Hi @siddhi-244 I've made the appropriate edits, kindly check and let me know what you think about it.

**Review by siddhi-244 — APPROVED** [review]
LGTM. Just try to add description in pr template

**Comment by abhilipsasahoo03** [comment]
> LGTM. Just try to add description in pr template

Okay sure!

**Comment by abhilipsasahoo03** [comment]
> LGTM. Just try to add description in pr template

Done. Let me know what you think.

**Comment by abhilipsasahoo03** [comment]
Hi @siddhi-244 just a trivial question. Can I create/work on a new issue in this repo while this one's still open?

**Comment by siddhi-244** [comment]
> Hi @siddhi-244 just a trivial question. Can I create/work on a new issue in this repo while this PR and its corresponding issue are still open?

Yes you can !

**Comment by Lakhankumawat** [comment]
@all-contributors please add @abhilipsasahoo03  code ,

**Pull request merged**
