### PR TITLE
Added the code for printing the matrix in wave form

### PR DESCRIPTION
**Pull request by Sakshi-1701**
## Related Issue
#1375 

## Proposed Changes
Added the code for printing a matrix in wave form. 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.

For a given 2D integer array/matrix of size m x n(where m is the number of rows and n is the number of columns), print the matrix in wave order, i.e. print the first column top to bottom, next column bottom to top, and so on.

- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Test case 1  | Test case 2     |
|
gssoc1 (2)
  | 
gssoc2 (2)
     |

### CODE REVIEW

**Comment by Sakshi-1701** [comment]
@Mrjoy832 Please review my PR.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please remove the exe file first !

**Comment by Sakshi-1701** [comment]
@siddhi-244 Done the changes. Please review.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Pull request merged**
