### PR TITLE
Subset Sum

### LINKED ISSUE #1289: Subset Sum
### Description

Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum. 

### Domain

Competitive Programming

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/LearnCPP/blob/main/.github/CODE_OF_CONDUCT.md) of LearnCPP.

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
-  Subset Sum | Backtracking
## Related Issue
- #1289 

## Proposed Changes
- Code to implement Subset Sum.
- Readme file for the same.

## Additional Info
- All kind of information is in the readme file as well as comment present in code file wherever necessary.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- I have implemented The Subset sum problem which is important concept as this problem is implemented using backtracking. Problems  bases on backtracking can only be solved by trying every possible configuration and each configuration is tried only once. 

- This concept is not yet implemented and it solves understanding about backtracking that can be used in subset  related problems.

- It fixes #1289 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1 |
| ----------- |
| Code  |
|Screenshot (561)|

| Screenshot #2 |
| ----------- |
|Output  |
|Screenshot (563)|

### CODE REVIEW

**Comment by Mrjoy832** [comment]
- Add some comments in cpp file 
- Change image in readme
- readme heading links are not properly implemented

**Comment by mdnazisharman2803** [comment]
Heading Link isn't working because I'm following the conventional format already present before contributing by me, they've added like 1, 2 3,4 serial number  their link isn't working either. If I don't put serial number it'll work. But just to see homogeneity I've still continued to add serial number... 


Image can't be changed in readme because that's not any famous problem that image is available everywhere, if you want I can atmax take screenshot from gfg site, as I always try to give original so I create from myself, sorry for my terrible writing. 

Comments are already present in cpp file , but still if you want some comment I'll add for sure
@Mrjoy832

**Comment by Mrjoy832** [comment]
> Heading Link isn't working because I'm following the conventional format already present before contributing by me, they've added like 1, 2 3,4 serial number their link isn't working either. If I don't put serial number it'll work. But just to see homogeneity I've still continued to add serial number...
> 
> Image can't be changed in readme because that's not any famous problem that image is available everywhere, if you want I can atmax take screenshot from gfg site, as I always try to give original so I create from myself, sorry for my terrible writing.
> 
> Comments are already present in cpp file , but still if you want some comment I'll add for sure @Mrjoy832

- All  Numbers in image are not clear ...add a new  fresh hand written image
-  remove heading link indexes

**Comment by mdnazisharman2803** [comment]
> > Heading Link isn't working because I'm following the conventional format already present before contributing by me, they've added like 1, 2 3,4 serial number their link isn't working either. If I don't put serial number it'll work. But just to see homogeneity I've still continued to add serial number...
> > Image can't be changed in readme because that's not any famous problem that image is available everywhere, if you want I can atmax take screenshot from gfg site, as I always try to give original so I create from myself, sorry for my terrible writing.
> > Comments are already present in cpp file , but still if you want some comment I'll add for sure @Mrjoy832
> 
> * All  Numbers in image are not clear ...add a new  fresh hand written image
> * remove all  heading link index

Okkk

**Comment by mdnazisharman2803** [comment]
@Mrjoy832  done can you check

**Comment by Mrjoy832** [comment]
image
Remove these points...as it's not working 

- Add image about describing workflow

**Comment by mdnazisharman2803** [comment]
> image Remove these points...as it's not working
> 
> * Add image about describing workflow

I've added that image about how it was working then you've said to change

**Comment by mdnazisharman2803** [comment]
I'm closing this better

**Comment by Mrjoy832** [comment]
> > image Remove these points...as it's not working
> > 
> > * Add image about describing workflow
> 
> I've added that image about how it was working then you've said to change

I said that in that image all numbers are not clear..so to insert fresh hand written image..You can add that image but with proper clearence

**Comment by Mrjoy832** [comment]
> I'm closing this better

Just re-write the previous image and insert

**Comment by mdnazisharman2803** [comment]
@Mrjoy832  now chcek

**Comment by Mrjoy832** [comment]
LGTM🌟

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]

**Comment by Lakhankumawat** [comment]
I'll give you level 2 if you modify existing README top section as well
Currently it looks like this 
image

It should look like https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SearchingAlgorithms/README.md

**Comment by mdnazisharman2803** [comment]
> I'll give you level 2 if you modify existing README top section as well Currently it looks like this image
> 
> It should look like https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SearchingAlgorithms/README.md

I'll definitely do it

**Comment by mdnazisharman2803** [comment]
@Lakhankumawat readme is modified as well as each and every single links have been fixed and clean readme is ready.

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
This is a demo REVIEW

**Comment by mdnazisharman2803** [comment]
@Lakhankumawat  i have preview it loooks fine where is change nedeed

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
> This is a demo REVIEW

Ignore , i was just showing mentors how to review prs properly .

**Pull request merged**
