### PR TITLE
Binding concept in C++

### PR DESCRIPTION
**Pull request by shr-code**
## Binding in C++
-  Added a new folder B-Binding where I discussed about Early and Late Binding in C++ with examples
- (issue number #1218  )

## Proposed Changes
- What is Binding?
- Early Binding and Late Binding

## Additional Info
- OOP is used commonly for software development. One major pillar of OOP is polymorphism. Early Binding and Late Binding are related to that. Early Binding occurs at compile time while Late Binding occurs at runtime. In method overloading, the bonding happens using the early binding. In method overriding, the bonding happens using the late binding. The difference between Early and Late Binding is that Early Binding uses the class information to resolve method calling while Late Binding uses the object to resolve method calling.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
earlybinding 
 latebinding

### CODE REVIEW

**Comment by shr-code** [comment]
@Mrjoy832

**Comment by shr-code** [comment]
@Lakhankumawat @siddhi-244 please review this

**Comment by shr-code** [comment]
@miraj0507 hey please review my pr

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by shr-code** [comment]
So is it ready to merge? @Lakhankumawat  @siddhi-244

**Comment by Mrjoy832** [comment]
> So is it ready to merge? @Lakhankumawat @siddhi-244

yes...you start  working on another issue.

**Comment by Lakhankumawat** [comment]
Remove your code from `B-Binding` and add it to `O-OOPS` .

**Comment by shr-code** [comment]
> Remove your code from `B-Binding` and add it to `O-OOPS` .

Done!!

**Comment by Lakhankumawat** [comment]
Delete `exe` files

**Comment by shr-code** [comment]
> Delete `exe` files

Deleted!

**Comment by shr-code** [comment]
@Lakhankumawat changes done

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
Contiuous Good Contribution , mention this pr number in your next pr which is open ,

**Pull request merged**
