### PR TITLE
Trie Implementation Done

### PR DESCRIPTION
**Pull request by bharat1999**
## Related Issue
- Issue #106

## Proposed Changes
- Implemented Trie to insert and search Non negative integes
- Implemented Trie to insert and search strings

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

I have implemented Trie to efficiently search and inserted integers and strings

- In case of non negative integers the time complexity for insert and search will be constant as we will do 32 computations only
- In case of strings the timec complexity for insert and search will be O(string_length) as we have to only iterate over the character of string to be inserted or searched

Open Issue LINK

https://github.com/Lakhankumawat/LearnCPP/issues/106

Test Details
I have run the test cases on GCC compiler and I run the following cases

Integer Trie

Inserted Array [  22, 10, 2, 8, 5, 3 ]
Array to be Searched [ 1, 2, 5, 10, 25, 0 ]

String Trie

Inserted Strings [ "code", "coder", "C++","GSSOC", "girlscript", "LearnCPP"]  
Strings to be Searched [ "coder", "codes", "C++", "GSSoc", "LearnCPP" ] 

My code is addition of a new Data Structure and it does not affect any other code of the project

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Integer Trie  | String Trie  |
| image  | image |

### CODE REVIEW

**Review by Lakhankumawat — COMMENTED** [review]
Code Looks Clean and GOOD other mentor will review the cheks for code compilation and working .

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Add a README or modify the existing README according to your trie implementation

**Comment by Lakhankumawat** [comment]
For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

**Comment by bharat1999** [comment]
I have updated the readme please review

**Review by miraj0507 — COMMENTED** [review]
Code works fine and looks good to me , good way of implementing trie. 
@n4i9kita kindle re review from your part this looks good to me.

**Comment by bharat1999** [comment]
@Lakhankumawat please merge if it is correct

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Delete the unnecessary exe files and Follow guidelines to modify your README further

**Comment by Lakhankumawat** [comment]
NO response from the contributor of this repo since  <h2>15 </h2> days

**Comment by bharat1999** [comment]
Sorry for the delay my exams got scheduled I will update it today itself

**Comment by Lakhankumawat** [comment]
your **today** is delayed for 4 days

**Comment by Lakhankumawat** [comment]
no pr activity closed #106

**Pull request closed without merging**
