### PR TITLE
Coin change

### PR DESCRIPTION
**Pull request by Shweta2024**
## Related Issue
- Coin Change #1229

## Proposed Changes
- Add Code of Coin Change
- Update README.md

## Additional Info
- [link of the Problem](https://leetcode.com/problems/coin-change/)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

We were supposed to find the minimum number of coins required to make an amount, provided that we can take a coin any number of times.

I have added the Problem Statement, Examples, an Explanation on how to approach this problem, a commented Code, Pseudo Code, and written the Time Complexity and Space Complexity. And finally updated the README.md.

This change helps to solve a very famous problem of Dynamic Programming i.e. Coin Change and this problem helps in understanding the concept of Dynamic Programming.

I coded this problem in VS Code and tested the given problem on the test cases in the range 1 <= coins.length <= 12 ,1 <= coins[i] <= 231 - 1, 0 <= amount <= 104. And it is working fine for them.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| coins = [1,2,5], amount = 11  | coins = [2], amount = 3    |
| image | image    |

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Resolve Conflicts and add some comments into code

**Comment by Shweta2024** [comment]
> Resolve Conflicts and add some comments into code

@Mrjoy832  The requested changes have been made. Please review my PR.

**Review by Mrjoy832 — APPROVED** [review]

**Comment by Mrjoy832** [comment]
LGTM🌟

**Review by Lakhankumawat — APPROVED** [review]
## LGTM ✨🎉

**Pull request merged**
