### PR TITLE
Palindrome linked list

### PR DESCRIPTION
**Pull request by DlVYANSH**
## Related Issue
- #343 

## Proposed Changes
- Code to check weather the given list is palindrome or not
- Readme file for the same

## Additional Info
- All information is in the readme

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [ ] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1 
Screenshot (238)
| Screenshot #2  |
Screenshot (239)

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
### Why TOO MANY COMMITS 🥲

**Comment by Lakhankumawat** [comment]
Anyone will fear to review it 
Don't make it difficult to mentors

**Comment by Lakhankumawat** [comment]
I have assigned some mentors they will review it shortly

**Comment by DlVYANSH** [comment]
> ### Why TOO MANY COMMITS 🥲

Sorry🥲

**Comment by DlVYANSH** [comment]
> I have assigned some mentors they will review it shortly

Sir there is not any mentors assigned @Lakhankumawat

**Comment by miraj0507** [comment]
This looks good to me.

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Since you are using a singly linked list 
Change Your code and README directory to `L-LinkedList/S-SinglyLinkedList` with README.md

Change Your File name `PalindromeLinkedList.cpp`


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

Typos in README ❌

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms)
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
image


There are conflicts in your PR

**Comment by Lakhankumawat** [comment]
Update README as requested , create a new PR and i'll merge it then

**Pull request closed without merging**
