### PR TITLE
Added Frequency Counting of all elements in an array

### PR DESCRIPTION
**Pull request by Lucifer4255**
Problem statement is to find frequency of all elements in an array in O(n) time complexity

## Related Issue
- #1 

## Proposed Changes
- As there are no problems on hashing in this section , I have added a simple hashing problem of counting frequency of elements in an array in O(n) time complexity and O(n) space complexity. 
## Additional Info
- Level - 1 problem

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Problem Statement is to find the count of frequencies of all elements in an array in O(n) time complexity and O(n) space complexity. 

As there are no solutions based on this problem so I have added this problem based on hashing with solution  

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
|  Screenshot #1     |   |
| ----------- | ----------- |
|   Output Test  |
|  
Screenshot (334)
|

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
@Lucifer4255  please read the Contributing guidelines [here](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md)

Please create a issue regarding this PR as each of PR is linked with an issue , it will be good for us to verify . 

And after creating the issue mention the issue name and number in **Related Issue**  for example it i type #1 then it will take me to issue 1

**Comment by Lucifer4255** [comment]
> @Lucifer4255 please read the Contributing guidelines [here](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md)
> 
> Please create a issue regarding this PR as each of PR is linked with an issue , it will be good for us to verify .
> 
> And after creating the issue mention the issue name and number in **Related Issue** for example it i type #1 then it will take me to issue 1
> 
> Thank you for your interest , Happy Coding !!

I have corrected my PR by changing the related issue. Kindly check my PR

**Comment by Lakhankumawat** [comment]
Please read the following steps [here](https://github.com/Lakhankumawat/LearnCPP#algorithms) for problem statement 

Your code is fine output is fine , just one more step and it will be merged

Thanks for your interest
Happy Coding !!

**Comment by Lucifer4255** [comment]
> Please read the following steps [here](https://github.com/Lakhankumawat/LearnCPP#algorithms) for problem statement
> 
> Your code is fine output is fine , just one more step and it will be merged
> 
> Thanks for your interest Happy Coding !!

I have updated my PR with the level of the problem please check

**Comment by Lakhankumawat** [comment]
> > Please read the following steps [here](https://github.com/Lakhankumawat/LearnCPP#algorithms) for problem statement
> > Your code is fine output is fine , just one more step and it will be merged
> > Thanks for your interest Happy Coding !!
> 
> I have updated my PR with the level of the problem please check

@Lucifer4255  please read the Contributing guidelines [here](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md)

**Comment by Lucifer4255** [comment]
> > > Please read the following steps [here](https://github.com/Lakhankumawat/LearnCPP#algorithms) for problem statement
> > > Your code is fine output is fine , just one more step and it will be merged
> > > Thanks for your interest Happy Coding !!
> > 
> > 
> > I have updated my PR with the level of the problem please check
> 
> @Lucifer4255 please read the Contributing guidelines [here](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md)

As per the guidelines I have updated the code with comments please check

**Comment by Lakhankumawat** [comment]
@dig9074vijay  please review this PR

**Comment by dig9074vijay** [comment]
Nice work @Lucifer4255! 
Thanks for contributing in our repo. I'm merging your PR.
Happy Coding!

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Lucifer4255   code

**Pull request merged**
