### PR TITLE
Sieve

### PR DESCRIPTION
**Pull request by RakshakSharan**
## Related Issue
- #289
## Proposed Changes
- Added sieve of eratosthenes algorithm in the MathematicalAlgorithms folder
- Updated README to contain information about this algorithm

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

   ## Description of my changes
-   Sieve of Eratosthenes is an algorithm for finding all prime numbers up to any given limit in an optimised way. In the 
  MathematicalAlgorithm folder I have added this sieve of eratosthenes folder.
-  I have updated the readme file of MathematicalAlgorithm folder to contain a detailed explanation along with the space and time complexity of this algorithm.
-  In the readme file I have also attached a gfg practice link of a problem based on this algorithm.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Prime numbers within a given range using sieve of eratosthenes algorithm      | Prime factorization of a number  using sieve of eratosthenes algorithm  |
| ----------- | ----------- |
|     |      |

### CODE REVIEW

**Comment by RakshakSharan** [comment]
## These are the outputs of the algorithm <br />

**Comment by RakshakSharan** [comment]
Sir  my pull request is descriptive and I have also checked the required
checklists.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You have added 2 problems in one pr.

**Comment by siddhi-244** [comment]
Also you haven't starred the repo and marked it as done in the checklist !

**Comment by Lakhankumawat** [comment]
Also you haven't mentioned issue number correctly in pr description

**Comment by Lakhankumawat** [comment]
Add # infront of your issue number

**Comment by RakshakSharan** [comment]
@Lakhankumawat @siddhi-244  I have done the required changes. Kindly review it.

**Comment by siddhi-244** [comment]
@RakshakSharan  there are 3 files ! Please see to it

**Comment by siddhi-244** [comment]
> > @RakshakSharan there are 3 files ! Please see to it
> 
> Mam I didn't get that. Can you please explain it further.

You have committed 3 files

**Comment by RakshakSharan** [comment]
> > > @RakshakSharan there are 3 files ! Please see to it
> > 
> > 
> > Mam I didn't get that. Can you please explain it further.
> 
> You have committed 3 files

Yes they are in the sieve of eratosthenes folder.

**Comment by siddhi-244** [comment]
So delete the extra ones

**Comment by RakshakSharan** [comment]
> So delete the extra ones

Yes mam deleted. Now there is only one file in the folder.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by siddhi-244** [comment]
Please resolve the merge conflicts

**Comment by RakshakSharan** [comment]
> Please resolve the merge conflicts

Ma'am it is showing my README file as the conflicting file. So what should I do?

**Comment by siddhi-244** [comment]
> > Please resolve the merge conflicts
> 
> Ma'am it is showing my README file as the conflicting file. So what should I do?

Just click on resolve conflicts. You can also watch some tutorials on utube

**Comment by siddhi-244** [comment]
Closing this pr!

**Pull request closed without merging**
