### PR TITLE
Huffman coding and update readme accordingly

### PR DESCRIPTION
**Pull request by VaishnaviMandloi**
## Related Issue
- #1048  Huffman Coding

## Proposed Changes
- added implementation code for huffman coding with comments (explanation) and sample expression.
- added a explanation in readme file with image.
 changes in readme

## Additional Info
- Huffman coding is a method of data compression that is independent of its data type. In which more common event is represented by shorter code and less common event is represent longer code.
- changes are made in only G-GreedyAlgorithms folder.
- 1st file : HuffdmanCoding.cpp
- 2nd file: readme.md
- tested with many input , screenshot of one of those is provided below.
- time complexity O(nlogn)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| code  | output     |
| code #1048 learncpp |   output #1048 learncpp|

### CODE REVIEW

**Comment by VaishnaviMandloi** [comment]
@Mrjoy832 what are the changes I have made in this ?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 what are the changes I have made in this ?

image

**Review by Lakhankumawat — APPROVED** [review]
LGTM ✨🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @VaishnaviMandloi  code ,

**Comment by Lakhankumawat** [comment]
Continuous Good Contribution ✨🎉

**Comment by VaishnaviMandloi** [comment]
> Continuous Good Contribution ✨🎉

Thank you 😊,  excited for more contributions

**Pull request merged**
