### PR TITLE
Create and display adjacency matrix of a graph

### PR DESCRIPTION
**Pull request by VaishnaviMandloi**
## Related Issue
- #1128   

## Proposed Changes
- added implementation code to create and display for Adjacency Matrix .
- added a explanation in readme file with image.

## Additional Info
- adjacency matrix is a matrix that maintain the information of adjacent vertices .
- A(i,j)= { 1 if there is a edge from vertex i to vertex j and 0 if there is no edge from vertex i to vertex j }
- changes are made in only G-Graph\Implementation folder.
- 1st file : AdjacencyMatrix.cpp
- 2nd file: readme.md
- tested with many input , screenshot of one of those is provided below.
- time complexity O(n^2)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1  | Screenshot #2  |
| ----------- | ----------- |
| output     | output     |
|
output #1128 learncpp
  |  
output 2 #1128 learncpp
   |

### CODE REVIEW

**Comment by Mrjoy832** [comment]
> ## Related Issue
> * [Create and display adjacency matrix of a graph #1128](https://github.com/Lakhankumawat/LearnCPP/issues/1128)   ( [Create and display adjacency matrix of a graph #1128](https://github.com/Lakhankumawat/LearnCPP/issues/1128)  )
> 
> ## Proposed Changes
> * added implementation code to create and display for Adjacency Matrix .
> * added a explanation in readme file with image.
> 
> ## Additional Info
> * adjacency matrix is a matrix that maintain the information of adjacent vertices .
> * A(i,j)= { 1 if there is a edge from vertex i to vertex j and 0 if there is no edge from vertex i to vertex j }
> * changes are made in only G-Graph\Implementation folder.
> * 1st file : AdjacencyMatrix.cpp
> * 2nd file: readme.md
> * tested with many input , screenshot of one of those is provided below.
> * time complexity O(n^2)
> 
> ## Checklist
> * [x]  ✅ My code follows the code style of this project.
> * [x]  📝 My change requires a change to the README.
> * [x]  🎀 I have updated the README accordingly.
> * [x]  👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
> * [x]  ✨ I have added tests to cover my changes.
> * [x]  🚩 All new and existing tests passed.
> * [x]  🌟 ed the repo
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> ## Output Screenshots
> | Screenshot #1 | Screenshot #2 | Screenshot #3 | | ----------- | ----------- | | code | output | output | | code #1128 learncpp | output #1128 learncpp | output 2 #1128 learncpp |

**useproper template....use proper heading on topic....remove code SS ,one keep Output SS, add related issue only once**

**Comment by VaishnaviMandloi** [comment]
@Mrjoy832 changes are made... plz review now

**Review by Lakhankumawat — APPROVED** [review]
Looks Awesome as always ✨🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @VaishnaviMandloi code ,

**Comment by VaishnaviMandloi** [comment]
> Looks Awesome as always ✨🎉

Thanks 😊,  excited for more contributions.

**Pull request merged**
