### PR TITLE
Updated README.md for QuickSort Problem

### PR DESCRIPTION
**Pull request by MRK04**
## Related Issue
- Readme for the issue no. #693

## Proposed Changes
- Added desciption for QuickSort problem

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
1.
image
2.
image
3.
image

### CODE REVIEW

**Comment by MRK04** [comment]
@Lakhankumawat pls review my PR.

**Comment by MRK04** [comment]
Hi @siddhi-244,  Pls review my PR.

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
You've made changes for QuickSort right ?

kindly  make the changes inside proper directory and delete these changes .

**Comment by MRK04** [comment]
> You've made changes for QuickSort right ?
> 
> kindly make the changes inside proper directory and delete these changes .

Do I need to create different Readme file for QuickSort?

**Comment by Lakhankumawat** [comment]
your title is `Updated README.md for R-Recursion folder #1032` Your README is related to Quicksort and it is inside recursion directory . somethings are wrong here correct these things up

**Comment by Lakhankumawat** [comment]
Change your readme directory to S-SortingAlgorithms

**Comment by Lakhankumawat** [comment]
That quicksort file was by mistake inside R-Recursion now i've deleted it .

**Comment by MRK04** [comment]
As mentioned, I have updated README.md in SortingAlgorithms directory.

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @MRK04 code ,

**Comment by Lakhankumawat** [comment]
I have seen your efforts and i wish to make this pr level 2 but gssoc program managers will yell at me saying why level 2 , so i recommend to mention this pr number in your next pr show some efforts there and i will increase level to 2 👍

**Pull request merged**
