### PR TITLE
Solved discounted price problem

### PR DESCRIPTION
**Pull request by Rishita489**
## Related Issue
- #1518 

## Proposed Changes
- Added a new file discountedPrice.cpp in the BruteForce Folder .

## Additional Info
- The program calculates the new price after applying discount on original price .

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| image

### CODE REVIEW

**Comment by Rishita489** [comment]
Where do I have to make changes in the readme ?

**Comment by siddhi-244** [comment]
> Where do I have to make changes in the readme ?

In your folder. Refer other prs

**Comment by Rishita489** [comment]
ok

**Comment by siddhi-244** [comment]
Any updates ?

**Comment by Rishita489** [comment]
Yes I will update the the PR in half an hour .

**Comment by Rishita489** [comment]
I have updated the readme file . You can review the PR and merge it .

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add table of contents and link them properly

**Comment by Rishita489** [comment]
Ok

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You have added cpp file in another folder and updated another readme. Can you refer other prs?

**Comment by Rishita489** [comment]
I have added the .cpp file in the Brute Force folder and updated the readme in the same folder .

**Comment by Rishita489** [comment]
image

**Comment by Rishita489** [comment]
image
 This is for table of contents

**Pull request closed without merging**
