### PR TITLE
Symmetric Matrix

### PR DESCRIPTION
**Pull request by aparnamittal**
## Related Issue
#1067

## Proposed Changes
A symmetric matrix in linear algebra is a square matrix that remains unaltered when its transpose is calculated. That means, a matrix whose transpose is equal to the matrix itself, is called a symmetric matrix.

image

## Additional Info
Symmetric Matrix Theorems:
**Theorem 1:** For any square matrix B with real elements, B + B^T is a symmetric matrix
**Theorem 2:** Any square matrix can be expressed as the sum of a skew-symmetric matrix and a symmetric matrix.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

### **Algorithm:**
1. Input from the user the order r,c of the matrix we wish to check
2. Input a matrix of size rxc from the user with the help of nested for loops and store it in a 2-D array of size rxc.
3. Set a variable flag = 0.
3. Using a nested for loop check if a[i][j] = a[j][i] , if not, set flag = 1 and break out of the loops.
4. Out of the loop check if flag = 0 then its symmetric matrix.
5. In the else condition, if flag = 1 then its not a symmetric matrix.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
For not symmetric matrix:
image

For symmetric matrix:
image

### CODE REVIEW

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Rename code file to `SymmetricMatrix`

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
@miraj0507  please review the code and conventions .

**Comment by aparnamittal** [comment]
sir I have made the changes

**Comment by aparnamittal** [comment]
Sir I have made the changes pls review my PR

**Review by miraj0507 — COMMENTED** [review]
The code runs fine, this can go into further scrutiny, this is simple and looks good to me

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
Continuous Good Contribution assigning Level2

**Pull request merged**
