### PR TITLE
Sliding Window Implementation with Explanation

### PR DESCRIPTION
**Pull request by Suryash-Jha**
Implemented and Explained about Sliding window. 
Checked it in my text editor and code is working perfectly fine.

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Hey @Suryash-Jha  , make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

**Comment by Lakhankumawat** [comment]
No Response From Contributor ...

**Comment by Lakhankumawat** [comment]
1. Short Description or CheckLists

Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Descriptoin -----------------------///

For contribution and more guidelines i would recommend you to go through this 
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.


///-----------------CheckList-------------------------///
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.


///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
No response from the contributor ??

**Comment by siddhi-244** [comment]
@Lakhankumawat  I think we should close this pr !

**Comment by Suryash-Jha** [comment]
Sorry sir... actually i was busy in some hackathons...so i forgot about
gssoc.
I will try to make my PR as directed as soon as possible.

Please, don't close this PR.
Thanks,
Suryash

**Pull request closed without merging**
