### PR TITLE
Perfectnumber

### PR DESCRIPTION
**Pull request by aparnamittal**
## Related Issue
- #547 

## Proposed Changes
- Check weather a number is a perfect number or not , A perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself. 

- Example:
6 is a positive number that is completely divisible by 1, 2, and 3. We know that the number is also divisible by itself but we will not include it in the addition of divisors. When we add these divisors (1 + 2 + 3 = 6), it gives 6, which is equal to the number that we have chosen. So, we say that 6 is a perfect number.

## Additional Info
Formula to check perfect number :
 If 2k -1 is prime for k>1, then 2k-1(2k -1) is a perfect number.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

1. Enter the number.
2. finding the divisors of the number. 
3. adding the devisors in variable sum.
4. checking weather a number is a perfect number or not. 
5. printing the result.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshot
image
image

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by siddhi-244** [comment]
Why have you committed 3 files ?

**Comment by aparnamittal** [comment]
Ma'am I have committed only two files.  Sort an Array of 0s, 1s and 2s  is contributed by someone else.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Why have you deleted Readme from different folder ?

**Comment by siddhi-244** [comment]
close this PR and create new one without any mistakes , or revert you last commit back

**Pull request closed without merging**
