### PR TITLE
Implementation of circular queue #207

### PR DESCRIPTION
**Pull request by rutika1823**
## Related Issue
-Implementation of circular queue #207
## Proposed Changes
- Added a code for Implementation of the circular queue

## Additional Info
- Tme complexity for enqueuing and dequeuing is  O(1).

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
code1
code2
code3

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by rutika1823** [comment]
I have uploaded readme file can u please check once again

**Comment by siddhi-244** [comment]
Can't see the readme file !

**Comment by rutika1823** [comment]
can u see now new readme file?

**Comment by rutika1823** [comment]
[Readme file for Implementation of circular queue using array (2).docx](https://github.com/Lakhankumawat/LearnCPP/files/8370946/Readme.file.for.Implementation.of.circular.queue.using.array.2.docx)

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
No there is no readme here

**Comment by siddhi-244** [comment]
Shall I close this pr?

**Comment by siddhi-244** [comment]
Closing this pr

**Pull request closed without merging**
