### PR TITLE
Segregate Even Odd Node Of LinkedList

### PR DESCRIPTION
**Pull request by Rahul-Kumar-prog**
## Related Issue
- Segregate Even Odd Node Of LinkedList ( #434  )

## Proposed Changes
- Even numbers apper in Front
- Odd numbers apper in End

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Sc
github image 1
github image
reenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
Change your code directory from `L-LinkedList/Segregate Even Odd Node Of LinkedList/Segregate_odd_even_node_of_linked_list.cpp` -> ` L-LinkedList/LinkedListOperations/SegregateEvenOdd.cpp` and README changes inside here as well

**Comment by Lakhankumawat** [comment]
Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

**Comment by Lakhankumawat** [comment]
Go through the commits you'll know what I have done.

**Comment by miraj0507** [comment]
The code seems to work fine, LGTM

**Review by Lakhankumawat — COMMENTED** [review]
LGTM

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Rahul-Kumar-prog  code ,

**Pull request merged**
