### PR TITLE
Update 1 in the README.md

### PR DESCRIPTION
**Pull request by n4i9kita**
## Related Issue
#6 

## Proposed Changes
1. Update 1 in the README.md
2. Empty readme have been added to each folder

## Next steps
1. Update 2 in README.md
2. Add content in the readme (present in subfolders)

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

### CODE REVIEW

**Review by Lakhankumawat — APPROVED** [review]
LGTM

**Comment by n4i9kita** [comment]
There are few issues in README.md. Will correct them by evening.
Empty readme's deserve some respect, will begin working on that too. :)

**Comment by n4i9kita** [comment]
@Lakhankumawat 

When I [Click here to save event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NDBqaDg3Z3JzaHAwYjVmcDJxNGw3OGszZDYga3VtYXdhdGxha2hhbjA3MDcyMDAxQG0&tmsrc=kumawatlakhan07072001%40gmail.com), this is what I get

__Could not find the requested event.__


Screenshot from 2022-02-27 22-26-34

**Comment by Lakhankumawat** [comment]
This issue will be kept in mind for further meets , I am not sure what caused this , you can try to resolve or suggestions are welcomed .

**Pull request merged**
