### PR TITLE
Updated Readme.md in F-Friend

### PR DESCRIPTION
**Pull request by shr-code**
links changed to correct one

## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number #1306  )

## Proposed Changes
- changed the links to correct one

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Comment by shr-code** [comment]
@Lakhankumawat  Earlier links were not working in Miscellaneous/F-Friend . Now I have fixed that.

**Comment by shr-code** [comment]
@Lakhankumawat ???

**Comment by Lakhankumawat** [comment]
Your contribution is great but not worth a level 😅 hope you understand , we cannot give level 1 to minor changes .

**Comment by shr-code** [comment]
can you give level 0 atleast?

**Comment by shr-code** [comment]
@Lakhankumawat

**Comment by shr-code** [comment]
@Lakhankumawat a level 0 is deserved ig

**Pull request merged**
