### PR TITLE
Added a program for reversing an array in A-Array Folder

### PR DESCRIPTION
**Pull request by shivanithorve01**
## Related Issue
- This PR is associated with issue #1160 and #1161 

## Proposed Changes
- Added a program for reversing an array in A-Array Folder

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Iterative Approach   | Recursive Approach     |
| 
image  | image     |

### CODE REVIEW

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Let me show you how to check the check list , there should be no space inside brackets like [x]
 `[x]`
- [x] Checklist
- [ ] Or you can just check them from outside without doing any of these
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

## 1. Starr the repo if you haven't !
2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?


///----------------------PR README --------------------///


You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
1. Complete Checks 
2. Modify README according to guidelines
3. Change Code and README directory to `A-Array/here your cpp file and README.md`
4. Remove Spacing in file naming and follow camel casing approach while naming files and creating headlines for README

**Comment by shivanithorve01** [comment]
@Lakhankumawat I made the changes. Please check it. 
Also My 2 PRs #81 and #496 are already merged. will you consider my PR for higher levels ?

**Comment by shivanithorve01** [comment]
@miraj0507 @Mrjoy832  Please review my PR.

**Comment by Mrjoy832** [comment]
Close Your issue ..it's already there

**Pull request closed without merging**
