### PR TITLE
Spiral Traversal of a Matrix

### PR DESCRIPTION
**Pull request by shr-code**
## Related Issue
- #1266 

## Proposed Changes
- Added spiral traversal of a matrix in A-Array
- Updated the readme accordingly

## Additional Info
- This problem statement is a question from GFG array must-do questions set. It is a medium level question 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
image

### CODE REVIEW

**Comment by shr-code** [comment]
@Lakhankumawat @siddhi-244 @Mrjoy832 Anyone?

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
1. You have committed 4 files. 
2. Follow the readme guidelines and add a table of contents. 
3. Explain the approach

**Comment by shr-code** [comment]
My code required changes in the existing readme. I have added the topic in the readme file.

**Comment by shr-code** [comment]
the algorithm is there with pictures to understand it better

**Comment by shr-code** [comment]
@siddhi-244 ?

**Comment by shr-code** [comment]
@siddhi-244 , @Lakhankumawat the files are different. My one is spiral traversal and the another one is anti spiral. Please review again. This is my 5th contribution to this repo. I hope I get a higher level.

**Comment by shr-code** [comment]
And again I raised the issue earlier and created a pr before him.

**Comment by shr-code** [comment]
@Mrjoy832 @Lakhankumawat

**Comment by shr-code** [comment]
@aditi944

**Comment by shr-code** [comment]
??? @siddhi-244

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You have committed 4 files ? What are they? Keep only readme and one .cpp file !

**Comment by shr-code** [comment]
i have read me and cpp file only but there was some error in fetching and by mistake i have committed

**Comment by siddhi-244** [comment]
> i have read me and cpp file only but there was some error in fetching and by mistake i have committed

So please remove that

**Comment by shr-code** [comment]
how to remove that? idk. Can you help?

**Comment by siddhi-244** [comment]
> how to remove that? idk. Can you help?

Take help from youtube. Also resolve the merge conflicts!

**Comment by shr-code** [comment]
@siddhi-244 can you check #1376 ?

**Comment by Mrjoy832** [comment]
Resolve Conflicts

**Comment by shr-code** [comment]
@Mrjoy832 check #1376 i have done all the changes in that branch . I will delete this branch

**Comment by shr-code** [comment]
Mentors I couldn't find how to remove commits and how to resolve the conflicts. I have done all the changes in the #1376 
Please review that. I am closing this pr. @siddhi-244 @Mrjoy832 @aditi944 @Lakhankumawat

**Pull request closed without merging**
