### PR TITLE
Segmented Sieve

### PR DESCRIPTION
**Pull request by deepu0201**
## Related Issue
- #79 

## Proposed Changes
- The segmented sieve cpp file is updated.

## Additional Info
- This is a segmented sieve problem which is very commonly used in competitive programming.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| Output 1      | 
| image |

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Remove the unnecessary spaces/gaps!

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Your code and contribution looks absolutely great @deepu0201  
Good Work 🎉✨

Few things you need to do before i merge your pr 
Move your folder structure inside here `LearnCPP/M-MathematicalAlgorithms/S-SegmentedSieve/Readme.md and  cpp file as well`

Rename `Readme.md` to `README.md`
Rename `Segmented_Sieve.cpp` to `SegmentedSieve.cpp`

**Comment by deepu0201** [comment]
@Lakhankumawat @siddhi-244 @miraj0507 please check, i have updated the files accordingly, please update me.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

Great Contribution....

**Comment by Lakhankumawat** [comment]
@all-contributors please add @deepu0201 code ,

**Pull request merged**
