### PR TITLE
Sorting Algorithm

### PR DESCRIPTION
**Pull request by lucy2512**
#1 Added some sorting algorithms.
  Hope you like it.

### CODE REVIEW

**Review by Lakhankumawat — COMMENTED** [review]
- There are still some changes you need to make but , i will make them on my own .

**Comment by Lakhankumawat** [comment]
Keep contributing 👍

**Comment by lucy2512** [comment]
Thanks for merging.
Can you please tell me the changes?
I will remember those  before making another PR.

**Comment by Lakhankumawat** [comment]
> Like there are bunch of things you can consider 

1. Adding some link to documentation and examples related to that so that new comers can easily get that thing 
2. Add comments in between code wherever needed so it is easy to understood
3. Add more spacing between codes to look it bit more nicerer

**Comment by Lakhankumawat** [comment]
Also you can check out my [`README PROFILE`](https://github.com/Lakhankumawat/LakhanKumawat) i have designed it whole myself . Do star it ...

**Comment by Lakhankumawat** [comment]
@all-contributors please add @lucy2512  code

**Comment by Lakhankumawat** [comment]
@all-contributors please add @lucy2512   code

**Pull request merged**
