### PR TITLE
Implement stack using array

### PR DESCRIPTION
**Pull request by varsha080**
## Related Issue
- Implementation of stack using array #102 

## Proposed Changes
Added a new file in Stack folder. The file has code of implementation of stack using array.

## Additional Info
- A stack can be implemented using array easily if we know some basic properties of stack.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Short Description or CheckLists
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

///------------------Descriptoin -----------------------///

For contribution and more guidelines i would recommend you to go through this
tutorial video of the project [here](https://youtu.be/7UgC3HDETRA), thanks.

///-----------------CheckList-------------------------///
Make sure your Pull Request is descriptive and complete the checklist .
I would recommend you to go through this tutorial video of the project [here](https://youtu.be/kIFwqp9B7pQ) ,thanks.

///------------------Description -----------------------///

Let me show you how to check the check list , there should be no space inside brackets like [x]
[x]

 Checklist
 Or you can just check them from outside without doing any of these
 ✨ I have added tests to cover my changes.
 🚩 All new and existing tests passed.
 🌟 ed the repo
Starr the repo if you haven't !
Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?
///----------------------PR README --------------------///

You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms)
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md)
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by siddhi-244** [comment]
Please do the changes asap or else your pr will be closed !

**Comment by varsha080** [comment]
> Please do the changes asap or else your pr will be closed !

Kindly have a look on the updated PR.

**Comment by siddhi-244** [comment]
> > Please do the changes asap or else your pr will be closed !
> 
> Kindly have a look on the updated PR.

The pr is not updated !

**Pull request closed without merging**
