### PR TITLE
Number of Islands

### PR DESCRIPTION
**Pull request by ishitagupta014**
## Related Issue
- Number of Islands #159 

## Proposed Changes
- Problem and Code in the file
- Readme (Contains Problem description and example and Approach)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- This pull request contains the solution of the issue Number of Islands #159 
- It fixes the issue created by me for the addition of a problem in G-Graphs Section
- It contains a readme file that contains problem Description and a file that contains code for the given problems with a proper description of comments.
- It has passed all the test cases and I have attached screenshots of two test cases as well.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Testcase1 | Testcase2   |
| 
Screenshot 2022-01-14 205915
 |  
univalued
   |

### CODE REVIEW

**Review by Lakhankumawat — CHANGES_REQUESTED** [review]
Your Code looks good but you can still modify your README 
You need to follow particular guidelines for your README , please follow
these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) 
also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) 
for more please go through these [here](https://youtu.be/7UgC3HDETRA)

**Comment by Lakhankumawat** [comment]
Similar Problem is present [here](https://leetcode.com/problems/number-of-islands/)  so justify in comments you have not copied from here !?

**Comment by Lakhankumawat** [comment]
1. Your Code looks good but you can still modify your README
2.  You need to follow particular guidelines for your README , please follow these guidelines [click here](https://github.com/Lakhankumawat/LearnCPP#to-add-programs-using-stl-follow-same-approach-as--algorithms) also you can see how your README should look like [see here](https://github.com/Lakhankumawat/LearnCPP/blob/main/S-SortingAlgorithms/README.md) for more please go through these [here](https://youtu.be/7UgC3HDETRA)
3. Starr the repo if you haven't !
4. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?
5. Please complete the checklists only if you have done them , i see you haven't starred the repo yet but checked it in checklist.

**Comment by ishitagupta014** [comment]
> 1. Starr the repo if you haven't !
> 2. Have you watched this [video](https://youtu.be/kIFwqp9B7pQ) ?
> 3. Please complete the checklists only if you have done them , i see you haven't starred the repo yet but checked it in checklist.

Hello @Lakhankumawat sir I have added more description of problem in README.md and have starred the repo as well. Please review my pr

**Comment by miraj0507** [comment]
Hello contributor, upon going through the PR it seems to have been beautifully presented but the description and also the images used without acknowledging the source, falls under plagiarism, Your description had 70% plagiarised when run through the software, It violates the guidelines.

**Comment by Lakhankumawat** [comment]
closed #159

**Pull request closed without merging**
