### PR TITLE
Generic tree creating and display

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Generic Tree Implementation.
## Related Issue
- #535 

## Proposed Changes
- Code to implement Generic Tree
- Readme file for the same.

## Additional Info
- All kind of information is in the readme file as well as comment present in code file wherever necessary.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- I have  implemented Generic tree which is  important concept as I have used dynamic array as children node of the root node and further parents may or may not consists  their own dynamic array representing their children basically it is n array  tree.

 - This concept is not yet implemented and it solves understanding of structure of a generic tree.
 - fixes issue #535 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Code  | Output     |
| Screenshot (454) | Screenshot (455)       |

### CODE REVIEW

**Review by Lakhankumawat — COMMENTED** [review]
LGTM , mentors will review your code , shortly

**Comment by Lakhankumawat** [comment]
Meanwhile you can make your Pull Request a little bit more descriptive

**Comment by mdnazisharman2803** [comment]
Done adding description kindly review  @siddhi-244

**Review by siddhi-244 — APPROVED** [review]
LGTM. You have starred the repo but haven't checked it in the check box.

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯

**Comment by Lakhankumawat** [comment]
@all-contributors please add @mdnazisharman2803  code ,

**Pull request merged**
