### PR TITLE
Find Normal and Trace of a matrix using array

### PR DESCRIPTION
**Pull request by aparnamittal**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )
- #527 

## Proposed Changes
I have added trace and normal of matrix 

## Additional Info
- properties of trace matrix 
 --> tr(A + B) = tr(A) +tr(B)
 --> tr(cA) = ctr(A)  ** c represents scalars
 --> tr(A) = tr(A^T)  ** T means transpose of matrix 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

The trace of a matrix A, defined by tr(A), is the sum of the diagonal elements of a matrix. Trace of a matrix is only possible for square matrix .
The normal of matrix is the sum of all the elements of a matrix and then the square root of sum.

I have taken two examples look at the output screenshot to understand 

I have  used code blocks to implement this code .

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots

| Screenshot #1 | output when we use 3X3 matrix :
image

|Screenshot #2  | output when we use 2X2 matrix : 
image

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Change your C++ file directory from `[A-Array/TwoD Array/TraceAndNormal.cpp]` to `[A-Array/TraceAndNormal.cpp]`

**Comment by aparnamittal** [comment]
sir I have made the changes pls review it

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Can uh add time complexity?

**Comment by aparnamittal** [comment]
Ma'am I have made the changes, pls review it.

**Review by siddhi-244 — APPROVED** [review]
LGTM. Just check the proper items in the check list.

**Comment by Lakhankumawat** [comment]
@all-contributors please add @aparnamittal code ,

**Pull request merged**
