### PR TITLE
Added remove duplicates from sorted array

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )
#1186  
## Proposed Changes

Given a sorted array our task is to remove duplicates from the array.

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Given an sorted array, the task is to remove the duplicates from the array. Added cpp file in the array repo and added readme file.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |

Images

Images1

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Put ticks on All needed boxes, follow proper description template

**Comment by Sulagna-Dutta-Roy** [comment]
kindly check . I've done all the changes

**Comment by Mrjoy832** [comment]
image
You have not followed the Code Style of project?...tick on it also

**Comment by Sulagna-Dutta-Roy** [comment]
Done

**Comment by Mrjoy832** [comment]
> Done

fix all those ...I mentioned

**Comment by Sulagna-Dutta-Roy** [comment]
Crossed all the boxes that needed

**Comment by Mrjoy832** [comment]
image

**Pull request closed without merging**
