### PR TITLE
Added basic array programs

### PR DESCRIPTION
**Pull request by prachi0011**
## Related Issue
-  Added basic array programs #1119 

## Proposed Changes
- Add all basic array programs
- Added README.me

## Additional Info
LearnCPP is for learning CPP from basic to advance, so I have added few basic array implementations for better understading of arrays. These codes goes from very basic, _how to take array elements from input_ to intermediate level. With these array questions, concept of looping will also improve as for traversing array we  use loops. These are programs I have added to repository. 
- InputArray : _Program to input an array and traversing through it,_
- SmallestLargest : _Program to find the smallest and largest elements from an array._
- MinDiffPair : _Program to find the minimum difference between pairs of elements of array._
- PalindromeArray : _Program to check if array is palindrome or not._
- ReverseArray : _This program to reverse array with out using an extra array._
- Array2D : _This program is to take a 2Darray input and traversing through it._
- RowwiseSum : _This program is to find the sum of 2Darray elements row wise._
- ColumnWiseSum : _This program is to find the sum of 2Darray elements column wise._
- SymmetricMatrix : _This program to check whether an 2Darray is symmetric matrix or not._

I have also added README.md file with algorithms or pseudo codes and also added some test cases for each program.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the README.
- [x] 🎀 I have updated the README accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots

| InputArray |
image
| SmallestLargest |
image
| MinDiffPair |
image
| PalindromeArray |
image
| ReverseArray |
image
| Array2D |
image
| RowwiseSum |
image
| ColumnWiseSum |
image
| SymmetricMatrix |
image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
GIve Proper Heading

**Comment by prachi0011** [comment]
> GIve Proper Heading

Done, you can check now.

**Comment by Mrjoy832** [comment]
image
give the heading regarding Your Problem

**Comment by prachi0011** [comment]
> image give the heading regarding Your Problem

Now I have give heading, kindly check it.

**Pull request closed without merging**
