### PR TITLE
2 pointer implementation on doubly linked list

### PR DESCRIPTION
**Pull request by Supratim2000**
## Related Issue
- Add Algorithms

## Proposed Changes
- Added 2 pointer on doubly linked list implementation code 

## Additional Info
- 2 pointer code was missing in this repository. So I thought it will be a great idea to add 2 pointer algorithm code

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/LearnCPP/blob/main/Contributing.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Added 2 pointer algorithm in LearnCPP repository

Coded 2 pointer approach on doubly linked list

2 pointer approach was missing in this repository

Added one test case and tested for input and verified the output

Tested on VS code

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| ----------- | ----------- |
two_pointer_on_doubly_linked_list
Image 573

### CODE REVIEW

**Comment by Supratim2000** [comment]
2 pointer on doubly linked list modified

**Comment by Supratim2000** [comment]
2 pointer approach added

**Comment by Lakhankumawat** [comment]
Seems great next time please mention the issue number i.e for this pull request it is #1 in **Related issues** section

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Supratim2000  code

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Supratim2000  code

**Pull request merged**
